# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/ for full options

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - errcheck      # Checks for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Checks for unused constants, variables, functions and types
    - gofmt         # Checks whether code was gofmt-ed
    - goimports     # Check import statements are formatted according to the 'goimport' command
    - misspell      # Finds commonly misspelled English words in comments
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - stylecheck    # Replacement for golint
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gosec         # Security-focused linter
    - exportloopref # Checks for pointers to enclosing loop variables
    - gocyclo       # Computes cyclomatic complexity
    - dupl          # Code clone detection
    - goconst       # Finds repeated strings that could be replaced by a constant
    - gocritic      # Comprehensive Go source code linter
    - prealloc      # Finds slice declarations that could potentially be preallocated
    - predeclared   # Find code that shadows one of Go's predeclared identifiers
    - nolintlint    # Reports ill-formed or insufficient nolint directives

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: indent-error-flow
        disabled: false
      - name: errorf
        disabled: false
  
  gosec:
    excludes:
      - G104 # Audit errors not checked - we have errcheck for this
  
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - goconst
    
    # Exclude known issues with embedded files
    - path: '(.+)_gen\.go'
      linters:
        - gocyclo
        - goconst
        - dupl
