POSTGRES_VERSION ?= 17
POSTGRES_IMAGE   ?= us-docker.pkg.dev/coder-v2-images-public/public/postgres:$(POSTGRES_VERSION)

GIT_TAG := $(shell git describe --tags --abbrev=0)
GIT_COMMIT := $(shell git describe --always)
BUILD_TIME := $(shell TZ='America/Chicago' date +"%m-%d-%y_%H:%M")
LD_BUILD_FLAGS=-ldflags=-X=github.com/Emyrk/chronicle/internal/version.GitTag=$(GIT_TAG)\ -X=github.com/Emyrk/chronicle/internal/version.GitCommit=$(GIT_COMMIT)\ -X=github.com/Emyrk/chronicle/internal/version.BuildTime=$(BUILD_TIME)

.PHONY: install
install:
	go install ./cmd/chronicle
	go install ./cmd/chronicled

.PHONY: wasm
wasm:
	GOOS=js GOARCH=wasm go build -tags wasm -o ./site/parser.wasm ./cmd/wasm/

.PHONY: serve
serve: wasm
	@echo "Starting development server at http://localhost:8080"
	@cd site && python3 -m http.server 8080

database/querier.go: database/sqlc.yaml database/dump.sql $(wildcard database/queries/*.sql)
	./database/generate.sh

.PHONY: test
test:
	gotestsum --format testname -- -race $$(go list ./... | grep -v cmd/wasm)

.PHONY: lint
lint:
	golangci-lint run

frontend/chronicle/dist: $(wildcard frontend/**)
	(cd frontend/chronicle; pnpm install; pnpm build)

.PHONY: develop
develop: frontend/chronicle/dist create-db
	go run --tags static $(LD_BUILD_FLAGS) ./cmd/chronicled server --dev-auth --jwt-secret-pem="dev"

.PHONY: build
build: build-backend frontend/chronicle/dist

.PHONY: build-backend
build-backend:
	go build --tags static  $(LD_BUILD_FLAGS) -o bin/chronicled ./cmd/chronicled

.PHONY: create-db
create-db:
	PGPASSWORD='postgres' createdb -U postgres -h localhost chronicle || true

.PHONY: test-postgres-docker
test-postgres-docker:
	docker rm -f test-postgres-docker-${POSTGRES_VERSION} || true

	docker pull ${POSTGRES_IMAGE}

	# Make sure to not overallocate work_mem and max_connections as each
	# connection will be allowed to use this much memory. Try adjusting
	# shared_buffers instead, if needed.
	#
	# - work_mem=8MB * max_connections=1000 = 8GB
	# - shared_buffers=2GB + effective_cache_size=1GB = 3GB
	#
	# This leaves 5GB for the rest of the system _and_ storing the
	# database in memory (--tmpfs).
	#
	# https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-WORK-MEM
	docker run \
		--env POSTGRES_PASSWORD=postgres \
		--env POSTGRES_USER=postgres \
		--env POSTGRES_DB=postgres \
		--env PGDATA=/tmp \
		--tmpfs /tmp \
		--publish 5432:5432 \
		--name test-postgres-docker-${POSTGRES_VERSION} \
		--restart no \
		--detach \
		--memory 16GB \
		${POSTGRES_IMAGE} \
		-c shared_buffers=2GB \
		-c effective_cache_size=1GB \
		-c work_mem=8MB \
		-c max_connections=1000 \
		-c fsync=off \
		-c synchronous_commit=off \
		-c full_page_writes=off \
		-c log_statement=all
	while ! pg_isready -h 127.0.0.1; do \
		echo "$$(date) - waiting for database to start"; \
		sleep 0.5; \
	done

frontend/chronicle/src/api/typesGenerated.ts: $(wildcard scripts/apitypings/*) $(shell find ./api/chroniclesdk $(FIND_EXCLUSIONS) -type f -name '*.go') go.mod go.sum
	# -C sets the directory for the go run command
	go run -C ./scripts/apitypings main.go > $@
	#(cd frontend/chronicle/ && pnpm exec biome format --write src/api/typesGenerated.ts)
	touch "$@"

# All files generated by the database should be added here, and this can be used
# as a target for jobs that need to run after the database is generated.
DB_GEN_FILES := \
	database/dump.sql \
	database/querier.go

database/dump.sql: $(wildcard database/migrations/*.sql)
	go run ./database/gen/dump/*.go

gen/db: $(DB_GEN_FILES)
.PHONY: gen/db

gen/proto:
	go generate ./api/chronicleproto/...
.PHONY: gen/proto

.PHONY: gen
gen: gen/db gen/proto wasm database/unique_constraint.go frontend/chronicle/src/api/typesGenerated.ts
	go generate ./...