// Code generated by 'guts'. DO NOT EDIT.

import type { GUID } from "@/lib/guid/guid";

// From chroniclesdk/log.go
export interface ActivityPeriod {
    readonly start?: PeriodMoment;
    readonly end?: PeriodMoment;
    readonly last_active?: PeriodMoment;
    readonly slain: boolean;
}

// From chroniclesdk/user.go
export interface AdminLog {
    readonly id: string;
    readonly owner_id: string;
    readonly owner_name: string;
    readonly description: string;
    readonly created_at: string;
    readonly state: string;
}

// From chroniclesdk/user.go
export interface AdminLogsResponse {
    readonly logs: readonly AdminLog[];
}

// From chroniclesdk/user.go
export interface AdminUsersResponse {
    readonly users: readonly User[];
}

// From chroniclesdk/authz.go
/**
 * AuthorizationRequest is a request to check multiple authorizations at once.
 */
export interface AuthorizationRequest {
    /**
     * Checks is a map of check names to SpiceDB-style object strings.
     * Keys are arbitrary identifiers returned in the response.
     * Values are in the format "type:id#permission", e.g.:
     *   - "raid_log:550e8400-e29b-41d4-a716-446655440000#view"
     *   - "instance:550e8400-e29b-41d4-a716-446655440000#edit"
     */
    readonly checks: Record<string, string>;
}

// From chroniclesdk/authz.go
/**
 * AuthorizationResponse is the response to an authorization request.
 * Keys correspond to the keys in the AuthorizationRequest.Checks map.
 * Values are true if the authorization check passed, false otherwise.
 */
export type AuthorizationResponse = Record<string, boolean>;

// From chroniclesdk/events.go
export interface ChronicleEncounterEvents {
    readonly encounter_id: string;
    readonly type: string;
    readonly payload: string;
    readonly start_time: string;
}

// From chroniclesdk/log.go
export type GUIDString = string;

// From chroniclesdk/log.go
export interface InstancePlayer {
    readonly name: string;
    readonly class: WoWHeroClasses;
    readonly race: WoWHeroRaces;
}

// From chroniclesdk/log.go
export interface InstanceUnit {
    readonly name: string;
    readonly owner: GUID | null;
    readonly entry: number;
}

// From chroniclesdk/job.go
export interface JobStatus {
    readonly id: number;
    readonly attempt: number;
    readonly max_attempts: number;
    readonly state: RiverJobState;
    readonly created_at: string;
    readonly scheduled_at: string;
    readonly attempted_at: string | null;
    readonly finalized_at: string | null;
    readonly errors: readonly RiverAttemptError[];
    readonly kind: string;
    readonly output?: Record<string, string>;
}

// From chroniclesdk/response.go
export interface LogUploadResponse {
    readonly log_id: string;
    readonly file_ids: readonly string[];
}

// From chroniclesdk/log.go
export interface PeriodMoment {
    readonly timestamp: string;
    readonly reason: string;
}

// From chroniclesdk/response.go
/**
 * Response represents a generic HTTP response.
 */
export interface Response {
    /**
     * Message is an actionable message that depicts actions the request took.
     * These messages should be fully formed sentences with proper punctuation.
     * Examples:
     * - "A user has been created."
     * - "Failed to create a user."
     */
    readonly message: string;
    /**
     * CallToAction is an optional field that suggests next steps to the user
     * based on the Message. This field is intended to guide users on what to do
     */
    readonly call_to_action?: string;
    /**
     * Detail is a debug message that provides further insight into why the
     * action failed. This information can be technical and a regular golang
     * err.Error() text.
     * - "database: too many open connections"
     * - "stat: too many open files"
     */
    readonly detail?: string;
}

// From rivertype/river_type.go
/**
 * AttemptError is an error from a single job attempt that failed due to an
 * error or a panic.
 */
export interface RiverAttemptError {
    /**
     * At is the time at which the error occurred.
     */
    readonly at: string;
    /**
     * Attempt is the attempt number on which the error occurred (maps to
     * Attempt on a job row).
     */
    readonly attempt: number;
    /**
     * Error contains the stringified error of an error returned from a job or a
     * panic value in case of a panic.
     */
    readonly error: string;
    /**
     * Trace contains a stack trace from a job that panicked. The trace is
     * produced by invoking `debug.Trace()`.
     *
     * In the case of a non-panic or an error produced as a stuck job was
     * rescued, this value will be an empty string.
     */
    readonly trace: string;
}

// From rivertype/river_type.go
export type RiverJobState = string;

// From chroniclesdk/user.go
export interface Session {
    readonly user_id: string;
    readonly session_id: string;
    readonly roles: readonly string[];
}

// From chroniclesdk/user.go
export interface User {
    readonly id: string;
    readonly username: string;
    readonly email: string;
    readonly roles: readonly string[];
    readonly created_at: string;
    readonly updated_at: string;
    readonly max_storage_bytes: number;
    readonly max_storage_bytes_updated: string;
    readonly consumed_storage_bytes: number;
}

// From chroniclesdk/youtube.go
export interface Video {
    readonly url: string;
    readonly exported_at: string;
    readonly results: readonly VideoTimestamp[];
}

// From chroniclesdk/youtube.go
export interface VideoTimestamp {
    readonly video_time_seconds: number;
    readonly raw_ocr: string;
    /**
     * ServerTime is the time shown on the in-game clock, like "17:56:08"
     */
    readonly server_time: string;
    /**
     * UTCTime is ServerTime adjusted by the user-specified offset to match UTC.
     * This is used to sync with encounter timestamps which are stored in UTC.
     */
    readonly utc_time?: string;
    readonly confidence: number;
}

// From types/date.go
/**
 * AddonDateFormat is the date format for addon created logs like `COMBATANT_INFO`
 */
export const WoWAddonDateFormat = "02.01.06 15:04:05";

// From types/constants.go
export type WoWAuraApplication = "Fades" | "Gains" | "Removed" | "Unknown";

export const WoWAuraApplications: WoWAuraApplication[] = ["Fades", "Gains", "Removed", "Unknown"];

// From types/constants.go
export type WoWCastActions = "begins to cast" | "casts" | "channels" | "fails casting";

export const WoWCastActionses: WoWCastActions[] = ["begins to cast", "casts", "channels", "fails casting"];

// From types/constants.go
export type WoWChangeDirection = "Gain" | "Loss";

export const WoWChangeDirections: WoWChangeDirection[] = ["Gain", "Loss"];

// From chroniclesdk/log.go
export interface WoWEncounter {
    readonly id: string;
    readonly instance_id: string;
    readonly boss: boolean;
    readonly name: string;
    readonly kill: boolean;
    readonly remaining?: readonly GUID[];
    readonly start_time: string;
    readonly end_time: string;
}

// From chroniclesdk/log.go
export interface WoWEncounterHostile {
    readonly id: GUID;
    readonly boss: boolean;
    readonly periods: readonly ActivityPeriod[];
}

// From types/constants.go
export type WoWEncounterType = "BOSS" | "TRASH" | "UNKNOWN";

export const WoWEncounterTypes: WoWEncounterType[] = ["BOSS", "TRASH", "UNKNOWN"];

// From chroniclesdk/log.go
export interface WoWEncounterWithHostiles extends WoWEncounter {
    readonly hostiles: readonly WoWEncounterHostile[];
}

// From types/constants.go
export type WoWEnvironmentType = "fall" | "lava";

export const WoWEnvironmentTypes: WoWEnvironmentType[] = ["fall", "lava"];

// From chroniclesdk/constants.go
export type WoWEventType = "aura" | "cast" | "damage" | "extra_attack" | "heal" | "resource_change" | "slain";

export const WoWEventTypes: WoWEventType[] = ["aura", "cast", "damage", "extra_attack", "heal", "resource_change", "slain"];

// From types/constants.go
export type WoWHeroClasses = "DRUID" | "HUNTER" | "MAGE" | "PALADIN" | "PRIEST" | "ROGUE" | "SHAMAN" | "UNKNOWN" | "WARLOCK" | "WARRIOR";

export const WoWHeroClasseses: WoWHeroClasses[] = ["DRUID", "HUNTER", "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "UNKNOWN", "WARLOCK", "WARRIOR"];

// From types/constants.go
export type WoWHeroGender = 3 | 2 | 0 | 1;

export const WoWHeroGenders: WoWHeroGender[] = [3, 2, 0, 1];

// From types/constants.go
export type WoWHeroRaces = "BloodElf" | "Dwarf" | "Gnome" | "Goblin" | "Human" | "NightElf" | "Orc" | "Scourge" | "Tauren" | "Troll" | "Unknown";

export const WoWHeroRaceses: WoWHeroRaces[] = ["BloodElf", "Dwarf", "Gnome", "Goblin", "Human", "NightElf", "Orc", "Scourge", "Tauren", "Troll", "Unknown"];

// From types/constants.go
export type WoWHitType = 4 | 512 | 32768 | 2048 | 16384 | 1024 | 128 | 262144 | 16 | 256 | 2 | 8192 | 65536 | 32 | 0 | 1 | 4096 | 64 | 131072 | 8 | 2097152 | 1048576 | 524288;

export const WoWHitTypes: WoWHitType[] = [4, 512, 32768, 2048, 16384, 1024, 128, 262144, 16, 256, 2, 8192, 65536, 32, 0, 1, 4096, 64, 131072, 8, 2097152, 1048576, 524288];

// From chroniclesdk/log.go
export interface WoWInstance {
    readonly id: string;
    readonly realm_id: string;
    readonly log_group_id: string;
    readonly name: string;
    readonly slug: string;
}

// From chroniclesdk/log.go
export interface WoWLogFile {
    readonly id: string;
    readonly owner: string;
    readonly wow_log_id: string;
    readonly hash: string;
    readonly size_bytes: number;
    readonly mime_type: string;
    readonly created_at: string;
    readonly updated_at: string;
    readonly storage_deleted_at?: string;
}

// From chroniclesdk/log.go
export interface WoWLogGroup {
    readonly id: string;
    readonly owner: string;
    readonly created_at: string;
    readonly updated_at: string;
    readonly files: readonly WoWLogFile[];
    // empty interface{} type, falling back to unknown
    readonly processing_output?: unknown;
}

// From chroniclesdk/log.go
export interface WoWLogGroupState extends WoWLogGroup {
    readonly status: JobStatus;
}

// From chroniclesdk/log.go
export interface WoWParsedInstance extends WoWInstance {
    readonly encounters: readonly WoWEncounterWithHostiles[];
    readonly units: Record<string, InstanceUnit>;
    readonly players: Record<string, InstancePlayer>;
}

// From chroniclesdk/log.go
export interface WoWParsedLogJobOutput {
    readonly instance_failures: Record<string, string>;
    readonly instances: readonly WoWSimpleParsedInstance[];
}

// From types/constants.go
export type WoWResource = "Energy" | "Focus" | "Happiness" | "Health" | "Mana" | "Rage";

export const WoWResources: WoWResource[] = ["Energy", "Focus", "Happiness", "Health", "Mana", "Rage"];

// From types/constants.go
export type WoWSchool = 64 | 4 | 16 | 2 | 8 | 0 | 1 | 32;

export const WoWSchools: WoWSchool[] = [64, 4, 16, 2, 8, 0, 1, 32];

// From chroniclesdk/log.go
export interface WoWSimpleParsedInstance extends WoWInstance {
    readonly encounters: readonly WoWEncounter[];
}

// From types/trailer.go
/**
 * TrailerEntry represents a single entry in the combat trailer
 */
export interface WoWTrailerEntry {
    readonly Amount: number | null;
    readonly HitType: WoWHitType;
}


