// @generated by protoc-gen-es v2.11.0
// @generated from file chronicle.proto (package chronicleproto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file chronicle.proto.
 */
export const file_chronicle = /*@__PURE__*/
  fileDesc("Cg9jaHJvbmljbGUucHJvdG8SDmNocm9uaWNsZXByb3RvIh0KCkhlbGxvV29ybGQSDwoHbWVzc2FnZRgBIAEoCUIvWi1naXRodWIuY29tL0VteXJrL2Nocm9uaWNsZS9hcGkvY2hyb25pY2xlcHJvdG9iBnByb3RvMw");

/**
 * Describes the message chronicleproto.HelloWorld.
 * Use `create(HelloWorldSchema)` to create a new message.
 */
export const HelloWorldSchema = /*@__PURE__*/
  messageDesc(file_chronicle, 0);

