import { Hono } from "hono";
import { html } from "hono/html";
import type { Env } from "../types";

const analyticsExplore = new Hono<{ Bindings: Env }>();

analyticsExplore.get("/internal/analytics/explore", (c) => {
  c.header("Cache-Control", "private, no-cache");
  return c.html(
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Explore Analytics · Chronicle Telemetry</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="" />
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
        {html`<style>
          :root{--bg:#101516;--panel:#171d1e;--line:#2d3a3c;--text:#edf3f3;--muted:#849396;--accent:#79c4d7;--gold:#d0ad72;--good:#7dc69b}
          *{box-sizing:border-box} body{margin:0;min-height:100vh;color:var(--text);background:radial-gradient(circle at 84% -10%,#254047 0,transparent 32rem),var(--bg);font-family:'Manrope',sans-serif}
          body::before{content:'';position:fixed;inset:0;pointer-events:none;opacity:.16;background-image:linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px);background-size:36px 36px;mask-image:linear-gradient(to bottom,#000,transparent 78%)}
          main{position:relative;width:min(1320px,calc(100% - 40px));margin:0 auto;padding:30px 0 64px} a{color:inherit;text-decoration:none}.mono,.eyebrow,.route,th{font-family:'IBM Plex Mono',monospace}
          header{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:22px}.eyebrow{color:var(--accent);font-size:10px;letter-spacing:.18em;text-transform:uppercase}h1{margin:7px 0 5px;font-size:clamp(29px,4vw,45px);letter-spacing:-.045em}header p{margin:0;color:var(--muted);font-size:13px}.back{padding:9px 12px;border:1px solid var(--line);border-radius:6px;background:#172022;font-size:12px;font-weight:700}
          .tabs{display:flex;gap:7px;overflow:auto;margin-bottom:16px;padding-bottom:3px}.tab{white-space:nowrap;padding:9px 13px;border:1px solid var(--line);border-radius:6px;background:#151c1d;color:#9ba9ab;font-size:11px;font-weight:700}.tab.active{border-color:#53747b;background:#1e3033;color:#dce8ea}
          .toolbar{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:13px;color:var(--muted);font-size:11px}.toolbar select{padding:8px 30px 8px 10px;border:1px solid var(--line);border-radius:5px;background:#172022;color:#d5dfe0;font:600 11px 'Manrope',sans-serif}
          .grid{display:grid;gap:13px}.summary{grid-template-columns:repeat(4,1fr);margin-bottom:13px}.stat{padding:17px;border:1px solid var(--line);border-radius:8px;background:linear-gradient(145deg,#1b2324,#151a1b)}.stat label{display:block;color:#829194;font-size:10px;font-weight:700;letter-spacing:.06em;text-transform:uppercase}.stat strong{display:block;margin:10px 0 4px;font-size:29px;letter-spacing:-.04em}.stat small{color:#67777a;font-size:10px}.route{color:var(--accent)}
          .panel{min-width:0;border:1px solid var(--line);border-radius:9px;background:linear-gradient(155deg,#192021f2,#14191af2);box-shadow:0 20px 55px #0003}.panel-head{display:flex;justify-content:space-between;gap:16px;padding:17px 18px 13px;border-bottom:1px solid #273234}.panel-title{font-size:13px;font-weight:800}.panel-subtitle{margin-top:4px;color:var(--muted);font-size:10px}.panel-tag{color:#647477;font:9px 'IBM Plex Mono',monospace;letter-spacing:.08em;text-transform:uppercase}
          .content-grid{grid-template-columns:minmax(0,1.2fr) minmax(330px,.8fr)}.content-grid.wide{grid-template-columns:1fr}.bars{padding:9px 18px 17px}.bar-row{display:grid;grid-template-columns:minmax(150px,220px) 1fr 66px;align-items:center;gap:12px;min-height:40px;border-bottom:1px solid #252f31;font-size:11px}.bar-row:last-child{border-bottom:0}.bar-label{font-weight:700}.track{height:6px;overflow:hidden;border-radius:9px;background:#263033}.track i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#4f818c,var(--accent))}.track.gold i{background:linear-gradient(90deg,#947348,var(--gold))}.value{text-align:right;color:#aebabc;font-family:'IBM Plex Mono',monospace}
          .table-wrap{overflow:auto;padding:0 7px 8px}table{width:100%;border-collapse:collapse;font-size:11px}th{padding:12px;color:#708083;font-size:9px;font-weight:500;letter-spacing:.08em;text-align:left;text-transform:uppercase}th.num,td.num{text-align:right}td{padding:11px 12px;border-top:1px solid #252f31;color:#aebabc}td strong{color:#e0e8e9}.server-link{color:#dce6e7;font-weight:700}.server-link:hover{color:var(--accent)}
          .instance-matrix{max-height:520px}.instance-matrix table{min-width:1000px}.instance-matrix th,.instance-matrix td{white-space:nowrap}.instance-matrix th:first-child,.instance-matrix td:first-child{position:sticky;left:0;z-index:2;background:#171d1e}.matrix-value{display:inline-block;min-width:42px;padding:4px 6px;border-radius:3px;background:#1e3033;color:#dbe7e9;font-family:'IBM Plex Mono',monospace;text-align:right}.matrix-empty{color:#566568}.coverage-note{color:#667679;font:9px 'IBM Plex Mono',monospace}
          .mode-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px;padding:16px 18px 4px}.mode{padding:14px;border:1px solid #2b3739;border-radius:7px;background:#151b1c}.mode span{color:var(--muted);font-size:10px}.mode strong{display:block;margin:5px 0 2px;font-size:24px}.coverage{padding:14px 18px 0;color:var(--muted);font-size:10px}.coverage b{float:right;color:var(--good);font-family:'IBM Plex Mono',monospace}.loading,.error{display:flex;align-items:center;justify-content:center;min-height:220px;padding:30px;color:var(--muted)}.error{color:#efa39e}
          @media(max-width:900px){.summary{grid-template-columns:1fr 1fr}.content-grid{grid-template-columns:1fr}}@media(max-width:580px){main{width:min(100% - 24px,1320px)}header{align-items:flex-start;flex-direction:column}.summary{grid-template-columns:1fr}.toolbar{align-items:flex-start;flex-direction:column}.bar-row{grid-template-columns:130px 1fr 54px}}
        </style>`}
      </head>
      <body>
        <main>
          <header>
            <div><div class="eyebrow">Chronicle signal room · drill down</div><h1 id="page-title">Explore analytics</h1><p id="page-subtitle">Loading a privacy-safe product breakdown…</p></div>
            <a class="back" href="/internal/analytics">← Analytics overview</a>
          </header>
          <nav class="tabs" aria-label="Analytics drill-downs">
            <a class="tab" data-focus="reports" href="?focus=reports">Reports & logs</a>
            <a class="tab" data-focus="armory" href="?focus=armory">Armory</a>
            <a class="tab" data-focus="leaderboards" href="?focus=leaderboards">Leaderboards</a>
            <a class="tab" data-focus="server" href="?focus=server">Server explorer</a>
          </nav>
          <div class="toolbar"><span id="period-label">Loading completed-day report…</span><div><select id="server-select" aria-label="Server" hidden></select> <select id="period" aria-label="Period"><option value="7">Last 7 days</option><option value="30" selected>Last 30 days</option><option value="90">Last 90 days</option></select></div></div>
          <section class="grid summary" id="summary"><div class="loading" style="grid-column:1/-1">Reading analytics</div></section>
          <section class="grid content-grid" id="content-grid">
            <article class="panel"><div class="panel-head"><div><div class="panel-title" id="primary-title">Usage breakdown</div><div class="panel-subtitle" id="primary-subtitle">Page views by safe route family</div></div><span class="panel-tag" id="primary-tag">Page views</span></div><div id="primary"><div class="loading">Building breakdown</div></div></article>
            <article class="panel"><div class="panel-head"><div><div class="panel-title" id="secondary-title">By server</div><div class="panel-subtitle" id="secondary-subtitle">Where this product is used</div></div><span class="panel-tag">Meaningful servers</span></div><div id="secondary"><div class="loading">Loading servers</div></div></article>
          </section>
        </main>
        {html`<script>
          const number=new Intl.NumberFormat('en-US');const compact=new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1});
          const esc=(v)=>String(v).replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
          const params=new URLSearchParams(location.search);let focus=params.get('focus')||'reports';let payload;
          const configs={
            reports:{title:'Reports & logs',subtitle:'From recent discovery through upload and individual /instances/* report views.',ids:['instance_reports','instance_collection','recent','logs_collection','log_detail','upload'],routes:{instance_reports:'/instances/*',instance_collection:'/instances',recent:'/recent',logs_collection:'/logs',log_detail:'/logs/*',upload:'/upload'}},
            armory:{title:'Armory',subtitle:'Separate player pages, guild pages, and the armory search surface.',ids:['armory_players','guilds','armory_search'],routes:{armory_players:'/armory/* players',guilds:'/g/* guilds',armory_search:'/armory search'}},
          };
          function family(id){return payload.productFamilies.find((row)=>row.id===id)||{id,label:id,pageViews:0,share:0}}
          function stat(label,value,note){return '<article class="stat"><label>'+esc(label)+'</label><strong>'+number.format(value)+'</strong><small>'+note+'</small></article>'}
          function familyBars(ids,routes){const rows=ids.map(family);const max=Math.max(...rows.map((r)=>r.pageViews),1);return '<div class="bars">'+rows.map((r)=>'<div class="bar-row"><span class="bar-label">'+esc(r.label)+'<br><small class="route">'+esc(routes[r.id]||'')+'</small></span><span class="track gold"><i style="width:'+Math.max(1,r.pageViews/max*100)+'%"></i></span><span class="value">'+compact.format(r.pageViews)+'</span></div>').join('')+'</div>'}
          function serverTable(ids){const rows=payload.serverProducts.filter((s)=>s.pageViews>=1000);return '<div class="table-wrap"><table><thead><tr><th>Server</th>'+ids.map((id)=>'<th class="num">'+esc(family(id).label)+'</th>').join('')+'</tr></thead><tbody>'+rows.map((s)=>'<tr><td><a class="server-link" href="?focus=server&host='+encodeURIComponent(s.hostname)+'">'+esc(s.hostname.replace('.chronicleclassic.com',''))+'</a></td>'+ids.map((id)=>'<td class="num">'+(s.families[id]?compact.format(s.families[id]):'—')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
          function renderProduct(config){const selected=config.ids.map(family);document.getElementById('page-title').textContent=config.title;document.getElementById('page-subtitle').textContent=config.subtitle;document.getElementById('summary').innerHTML=selected.map((r)=>stat(r.label,r.pageViews,'page views · '+(r.share*100).toFixed(1)+'% of traffic')).join('');document.getElementById('primary-title').textContent=config.title+' route mix';document.getElementById('primary-subtitle').textContent='Explicit route patterns, grouped without identifiers';document.getElementById('primary').innerHTML=familyBars(config.ids,config.routes);document.getElementById('secondary-title').textContent=config.title+' by server';document.getElementById('secondary-subtitle').textContent='Compare the same route families across servers';document.getElementById('secondary').innerHTML=serverTable(config.ids)}
          function leaderboardServerMatrix(data){const servers=data.servers.filter((server)=>server.totalPageViews>0);const labels=data.instances.map((row)=>row.label);const knownServers=new Set(payload.serverProducts.map((server)=>server.hostname));const value=(server,label)=>{const row=server.instances.find((item)=>item.label===label);return row?row.pageViews:0};const head='<tr><th>Instance</th>'+servers.map((server)=>{const name=esc(server.hostname.replace('.chronicleclassic.com',''));const label=knownServers.has(server.hostname)?'<a class="server-link" href="?focus=server&host='+encodeURIComponent(server.hostname)+'">'+name+'</a>':name;return '<th class="num">'+label+'<br><span class="coverage-note">'+(server.coverage*100).toFixed(1)+'%</span></th>'}).join('')+'</tr>';const total='<tr><td><strong>All leaderboard views</strong></td>'+servers.map((server)=>'<td class="num"><span class="matrix-value">'+compact.format(server.totalPageViews)+'</span></td>').join('')+'</tr>';const rows=labels.map((label)=>'<tr><td><strong>'+esc(label)+'</strong></td>'+servers.map((server)=>{const views=value(server,label);return '<td class="num">'+(views?'<span class="matrix-value">'+compact.format(views)+'</span>':'<span class="matrix-empty">—</span>')+'</td>'}).join('')+'</tr>').join('');return '<div class="table-wrap instance-matrix"><table><thead>'+head+'</thead><tbody>'+total+rows+'</tbody></table></div>'}

          function renderLeaderboards(){document.getElementById('content-grid').classList.add('wide');const data=payload.leaderboards;document.getElementById('page-title').textContent='Leaderboards';document.getElementById('page-subtitle').textContent='Raid demand and statistics versus speedruns, without player-level data.';document.getElementById('summary').innerHTML=stat('Leaderboard views',data.totalPageViews,'all leaderboard and ranking routes')+stat('Classified URLs',data.classifiedPageViews,(data.coverage*100).toFixed(2)+'% coverage')+data.modes.map((r)=>stat(r.label,r.pageViews,(r.share*100).toFixed(1)+'% of classified views')).join('');const max=Math.max(...data.instances.map((r)=>r.pageViews),1);document.getElementById('primary-title').textContent='Raid categories';document.getElementById('primary-subtitle').textContent='Instance selection encoded in leaderboard URLs';document.getElementById('primary').innerHTML='<div class="bars">'+data.instances.slice(0,12).map((r)=>'<div class="bar-row"><span class="bar-label">'+esc(r.label)+'</span><span class="track"><i style="width:'+Math.max(1,r.pageViews/max*100)+'%"></i></span><span class="value">'+compact.format(r.pageViews)+'</span></div>').join('')+'</div>';document.getElementById('secondary-title').textContent='Instances by subdomain';document.getElementById('secondary-subtitle').textContent='Every classified leaderboard instance split across Chronicle servers';document.getElementById('secondary').innerHTML=leaderboardServerMatrix(data)}
          function serverOptions(){const select=document.getElementById('server-select');select.hidden=false;select.innerHTML=payload.serverProducts.filter((s)=>s.pageViews>0).map((s)=>'<option value="'+esc(s.hostname)+'">'+esc(s.hostname.replace('.chronicleclassic.com',''))+'</option>').join('');const requested=params.get('host');if(requested&&payload.serverProducts.some((s)=>s.hostname===requested))select.value=requested;select.onchange=()=>{params.set('focus','server');params.set('host',select.value);history.replaceState(null,'','?'+params);renderServer()}}
          function renderServer(){if(!payload.serverProducts.length){const msg='<div class="error">No server data returned for this period.</div>';document.getElementById('summary').innerHTML=msg;document.getElementById('primary').innerHTML=msg;document.getElementById('secondary').innerHTML=msg;return}serverOptions();const host=document.getElementById('server-select').value;const server=payload.serverProducts.find((s)=>s.hostname===host)||payload.serverProducts[0];const rows=payload.productFamilies.map((f)=>({...f,pageViews:server.families[f.id]||0})).filter((f)=>f.pageViews>0).sort((a,b)=>b.pageViews-a.pageViews);const max=Math.max(...rows.map((r)=>r.pageViews),1);document.getElementById('page-title').textContent=server.hostname.replace('.chronicleclassic.com','')+' server';document.getElementById('page-subtitle').textContent='Full privacy-safe product mix for one Chronicle property.';document.getElementById('summary').innerHTML=stat('Total page views',server.pageViews,'selected server')+stat('Instance reports',server.families.instance_reports||0,'/instances/*')+stat('Armory players',server.families.armory_players||0,'/armory/*')+stat('Guild pages',server.families.guilds||0,'/g/*');document.getElementById('primary-title').textContent='Complete product mix';document.getElementById('primary-subtitle').textContent='Every classified route family on this server';document.getElementById('primary').innerHTML='<div class="bars">'+rows.map((r)=>'<div class="bar-row"><span class="bar-label">'+esc(r.label)+'</span><span class="track"><i style="width:'+Math.max(1,r.pageViews/max*100)+'%"></i></span><span class="value">'+compact.format(r.pageViews)+'</span></div>').join('')+'</div>';document.getElementById('secondary-title').textContent='Key route surfaces';document.getElementById('secondary-subtitle').textContent='Explicit paths requested for comparison';document.getElementById('secondary').innerHTML=serverTable(['instance_reports','armory_players','guilds','armory_search'])}
          function render(){document.querySelectorAll('.tab').forEach((el)=>el.classList.toggle('active',el.dataset.focus===focus));document.getElementById('content-grid').classList.remove('wide');document.getElementById('server-select').hidden=true;if(focus==='leaderboards')renderLeaderboards();else if(focus==='server')renderServer();else renderProduct(configs[focus]||configs.reports)}
          async function load(){try{const days=document.getElementById('period').value;const response=await fetch('/internal/api/v1/analytics/dashboard?days='+days);payload=await response.json();if(!response.ok)throw new Error(payload.error||'Request failed');document.getElementById('period-label').textContent=payload.period.start+' – '+payload.period.end+' · '+payload.timezone;render()}catch(error){const msg='<div class="error">'+esc(error.message||'Unable to load analytics')+'</div>';document.getElementById('summary').innerHTML=msg;document.getElementById('primary').innerHTML=msg;document.getElementById('secondary').innerHTML=msg}}
          document.getElementById('period').addEventListener('change',load);load();
        </script>`}
      </body>
    </html>
  );
});

export default analyticsExplore;
