// Code generated by scripts/hostilegen; DO NOT EDIT.
// Source: https://github.com/azerothcore/database-wotlk/

package instances

import (
	"github.com/Emyrk/chronicle/combatlog/parser/common/instances"
)

// KarazhanHostiles returns creature entry IDs for Karazhan (map 532).
func KarazhanHostiles() map[uint32]instances.Identity {
	hostile := make(map[uint32]instances.Identity)
	instances.LoadAdds(hostile, map[uint32]string{
		15384: "OLDWorld Trigger (DO NOT DELETE)",
		15547: "Spectral Charger",
		15548: "Spectral Stallion",
		15551: "Spectral Stable Hand",
		16153: "Berthold",
		16159: "Calliard",
		16169: "Hastings",
		16170: "Coldmist Stalker",
		16171: "Coldmist Widow",
		16173: "Shadowbat",
		16174: "Greater Shadowbat",
		16175: "Vampiric Shadowbat",
		16176: "Shadowbeast",
		16177: "Dreadbeast",
		16178: "Phase Hound",
		16388: "Koren",
		16389: "Spectral Apprentice",
		16406: "Phantom Attendant",
		16407: "Spectral Servant",
		16408: "Phantom Valet",
		16409: "Phantom Guest",
		16410: "Spectral Retainer",
		16411: "Spectral Chef",
		16412: "Ghostly Baker",
		16414: "Ghostly Steward",
		16415: "Skeletal Waiter",
		16424: "Spectral Sentry",
		16425: "Phantom Guardsman",
		16426: "Bennett",
		16459: "Wanton Hostess",
		16460: "Night Mistress",
		16461: "Concubine",
		16468: "Spectral Patron",
		16470: "Ghostly Philanthropist",
		16471: "Skeletal Usher",
		16472: "Phantom Stagehand",
		16473: "Spectral Performer",
		16481: "Ghastly Haunt",
		16482: "Trapped Soul",
		16485: "Arcane Watchman",
		16488: "Arcane Anomaly",
		16489: "Chaotic Sentience",
		16491: "Mana Feeder",
		16492: "Syphoner",
		16504: "Arcane Protector",
		16525: "Spell Shade",
		16526: "Sorcerous Shade",
		16529: "Magical Horror",
		16530: "Mana Warp",
		16539: "Homunculus",
		16540: "Shadow Pillager",
		16544: "Ethereal Thief",
		16545: "Ethereal Spellfilcher",
		16595: "Fleshbeast",
		16596: "Greater Fleshbeast",
		16806: "Ebonlocke",
		16811: "Sebastian",
		16813: "Wravien",
		16814: "Gradav",
		16815: "Kamsis",
		17168: "Shade of Aran Teleport N",
		17169: "Shade of Aran Teleport S",
		17170: "Shade of Aran Teleport E",
		17171: "Shade of Aran Teleport W",
		17172: "Shade of Aran Teleport NE",
		17173: "Shade of Aran Teleport SE",
		17174: "Shade of Aran Teleport SW",
		17175: "Shade of Aran Teleport NW",
		17176: "Shade of Aran Teleport Center",
		17208: "Chess Square, WHITE (DND)",
		17211: "Human Footman",
		17260: "Nightbane Helper Target",
		17305: "Chess Square, BLACK (DND)",
		17316: "Chess Square, OUTSIDE BLACK (DND)",
		17317: "Chess Square, OUSIDE WHITE (DND)",
		17459: "Chess Waiting Room (DND)",
		17469: "Orc Grunt",
		17518: "Ythyar",
		17644: "Infernal Target",
		17645: "Infernal Relay",
		17660: "Skeletal Gryphon",
		18654: "Crowd Murmur Helper",
		21160: "Conjured Water Elemental",
		21664: "Human Charger",
		21682: "Human Cleric",
		21683: "Human Conjurer",
		21684: "King Llane",
		21726: "Summoned Daemon",
		21747: "Orc Necrolyte",
		21748: "Orc Wolf",
		21750: "Orc Warlock",
		21752: "Warchief Blackhand",
		21921: "Chess - Sound Bunny",
		22519: "Chess Piece: Karazhan Invisible Stalker",
		22523: "Karazhan - Chess, Victory Dummy Tool",
		22524: "Karazhan - Chess, Victory Controller",
	})
	instances.LoadBosses(hostile, map[uint32]string{
		15687: "Moroes",
		15688: "Terestian Illhoof",
		15689: "Netherspite",
		15690: "Prince Malchezaar",
		15691: "The Curator",
		16151: "Midnight",
		16179: "Hyakiss the Lurker",
		16180: "Shadikith the Glider",
		16181: "Rokad the Ravager",
		16457: "Maiden of Virtue",
		16524: "Shade of Aran",
		16812: "Barnes",
		16816: "Echo of Medivh",
		17161: "Blizzard (Shade of Aran)",
		17225: "Nightbane",
		22520: "Chess Piece: Status Bar",
	})
	return hostile
}

var KarazhanFactory = &instances.CommonFactory{
	Name:      "Karazhan",
	ZoneNames: []string{"karazhan"},
	MapIDs:    []uint32{532},
	Hostiles:  instances.FromMap(KarazhanHostiles()),
}

// HyjalSummitHostiles returns creature entry IDs for Hyjal Summit (map 534).
func HyjalSummitHostiles() map[uint32]instances.Identity {
	hostile := make(map[uint32]instances.Identity)
	instances.LoadAdds(hostile, map[uint32]string{
		3794:  "Druid of the Talon",
		3795:  "Druid of the Claw",
		17919: "Alliance Footman",
		17920: "Alliance Knight",
		17921: "Alliance Rifleman",
		17922: "Alliance Sorceress",
		17928: "Alliance Priest",
		17931: "Alliance Peasant",
		17932: "Horde Grunt",
		17933: "Tauren Warrior",
		17934: "Horde Headhunter",
		17935: "Horde Witch Doctor",
		17936: "Horde Shaman",
		17937: "Horde Peon",
		17943: "Night Elf Archer",
		17944: "Dryad",
		17945: "Night Elf Huntress",
		18485: "Night Elf Ancient of War",
		18486: "Night Elf Ancient of Lore",
		18487: "Night Elf Ancient Protector",
		18502: "Night Elf Wisp",
		22418: "Archimonde Channel Target",
	})
	instances.LoadBosses(hostile, map[uint32]string{
		17772: "Lady Jaina Proudmoore",
		17852: "Thrall",
		17948: "Tyrande Whisperwind",
		17968: "Archimonde",
	})
	return hostile
}

var HyjalSummitFactory = &instances.CommonFactory{
	Name:      "Hyjal Summit",
	ZoneNames: []string{"hyjal summit", "the battle for mount hyjal"},
	MapIDs:    []uint32{534},
	Hostiles:  instances.FromMap(HyjalSummitHostiles()),
}

// MagtheridonsLairHostiles returns creature entry IDs for Magtheridon's Lair (map 544).
func MagtheridonsLairHostiles() map[uint32]instances.Identity {
	hostile := make(map[uint32]instances.Identity)
	instances.LoadAdds(hostile, map[uint32]string{
		15384: "OLDWorld Trigger (DO NOT DELETE)",
		17376: "Hellfire Raid Trigger",
		17474: "Target Trigger",
		19871: "World Trigger (Not Immune NPC)",
		21252: "World Trigger (Not Immune PC)",
	})
	instances.LoadBosses(hostile, map[uint32]string{
		17256: "Hellfire Channeler",
		17257: "Magtheridon",
		18829: "Hellfire Warder",
	})
	return hostile
}

var MagtheridonsLairFactory = &instances.CommonFactory{
	Name:      "Magtheridon's Lair",
	ZoneNames: []string{"magtheridon's lair"},
	MapIDs:    []uint32{544},
	Hostiles:  instances.FromMap(MagtheridonsLairHostiles()),
}

// SerpentshrineCavernHostiles returns creature entry IDs for Serpentshrine Cavern (map 548).
func SerpentshrineCavernHostiles() map[uint32]instances.Identity {
	hostile := make(map[uint32]instances.Identity)
	instances.LoadAdds(hostile, map[uint32]string{
		21218: "Vashj'ir Honor Guard",
		21220: "Coilfang Priestess",
		21221: "Coilfang Beast-Tamer",
		21224: "Tidewalker Depth-Seer",
		21225: "Tidewalker Warrior",
		21226: "Tidewalker Shaman",
		21227: "Tidewalker Harpooner",
		21228: "Tidewalker Hydromancer",
		21229: "Greyheart Tidecaller",
		21230: "Greyheart Nether-Mage",
		21231: "Greyheart Shield-Bearer",
		21232: "Greyheart Skulker",
		21246: "Serpentshrine Sporebat",
		21251: "Underbog Colossus",
		21253: "Tainted Water Elemental",
		21260: "Purified Water Elemental",
		21263: "Greyheart Technician",
		21301: "Coilfang Shatterer",
		21339: "Coilfang Hate-Screamer",
		21689: "Coilfang Frenzy Corpse",
		21863: "Serpentshrine Lurker",
		21873: "Coilfang Guardian",
		21918: "Coilfang Guardian (1)",
		21933: "Hydross Beam Helper",
		21934: "Hydross Cleansing Field Helper",
		22057: "Coilfang Raid Control Emote Stalker",
	})
	instances.LoadBosses(hostile, map[uint32]string{
		21212: "Lady Vashj",
		21213: "Morogrim Tidewalker",
		21214: "Fathom-Lord Karathress",
		21215: "Leotheras the Blind",
		21216: "Hydross the Unstable",
		21217: "The Lurker Below",
	})
	return hostile
}

var SerpentshrineCavernFactory = &instances.CommonFactory{
	Name:      "Serpentshrine Cavern",
	ZoneNames: []string{"serpentshrine cavern"},
	MapIDs:    []uint32{548},
	Hostiles:  instances.FromMap(SerpentshrineCavernHostiles()),
}

// TempestKeepHostiles returns creature entry IDs for Tempest Keep (map 550).
func TempestKeepHostiles() map[uint32]instances.Identity {
	hostile := make(map[uint32]instances.Identity)
	instances.LoadAdds(hostile, map[uint32]string{
		12999: "World Invisible Trigger",
		15384: "OLDWorld Trigger (DO NOT DELETE)",
		20031: "Bloodwarder Legionnaire",
		20032: "Bloodwarder Vindicator",
		20033: "Astromancer",
		20034: "Star Scryer",
		20035: "Bloodwarder Marshal",
		20036: "Bloodwarder Squire",
		20037: "Tempest Falconer",
		20038: "Phoenix-Hawk Hatchling",
		20039: "Phoenix-Hawk",
		20040: "Crystalcore Devastator",
		20041: "Crystalcore Sentinel",
		20042: "Tempest-Smith",
		20043: "Apprentice Star Scryer",
		20044: "Novice Astromancer",
		20046: "Astromancer Lord",
		20047: "Crimson Hand Battle Mage",
		20048: "Crimson Hand Centurion",
		20049: "Crimson Hand Blood Knight",
		20050: "Crimson Hand Inquisitor",
		20052: "Crystalcore Mechanic",
		22515: "World Trigger",
		22517: "World Trigger (Large AOI)",
	})
	instances.LoadBosses(hostile, map[uint32]string{
		18805: "High Astromancer Solarian",
		19514: "Al'ar",
		19516: "Void Reaver",
		19622: "Kael'thas Sunstrider",
		20060: "Lord Sanguinar",
		20062: "Grand Astromancer Capernian",
		20063: "Master Engineer Telonicus",
		20064: "Thaladred the Darkener",
	})
	return hostile
}

var TempestKeepFactory = &instances.CommonFactory{
	Name:      "Tempest Keep",
	ZoneNames: []string{"tempest keep", "the eye"},
	MapIDs:    []uint32{550},
	Hostiles:  instances.FromMap(TempestKeepHostiles()),
}

// BlackTempleHostiles returns creature entry IDs for Black Temple (map 564).
func BlackTempleHostiles() map[uint32]instances.Identity {
	hostile := make(map[uint32]instances.Identity)
	instances.LoadAdds(hostile, map[uint32]string{
		22515: "World Trigger",
		22517: "World Trigger (Large AOI)",
		22844: "Ashtongue Battlelord",
		22845: "Ashtongue Mystic",
		22846: "Ashtongue Stormcaller",
		22847: "Ashtongue Primalist",
		22853: "Illidari Defiler",
		22855: "Illidari Nightlord",
		22869: "Illidari Boneslicer",
		22873: "Coilskar General",
		22874: "Coilskar Harpooner",
		22875: "Coilskar Sea-Caller",
		22876: "Coilskar Soothsayer",
		22877: "Coilskar Wrangler",
		22878: "Aqueous Lord",
		22879: "Shadowmoon Reaver",
		22880: "Shadowmoon Champion",
		22882: "Shadowmoon Deathshaper",
		22883: "Aqueous Spawn",
		22884: "Leviathan",
		22885: "Dragon Turtle",
		22886: "Black Temple Captive",
		22939: "Temple Concubine",
		22945: "Shadowmoon Blood Mage",
		22946: "Shadowmoon War Hound",
		22953: "Wrathbone Flayer",
		22954: "Illidari Fearbringer",
		22955: "Charming Courtesan",
		22956: "Sister of Pain",
		22957: "Priestess of Dementia",
		22959: "Spellbound Attendant",
		22960: "Dragonmaw Wyrmcaller",
		22962: "Priestess of Delight",
		22963: "Bonechewer Worker",
		22964: "Sister of Pleasure",
		22965: "Enslaved Servant",
		22984: "Black Temple Trigger",
		23018: "Shadowmoon Houndmaster",
		23028: "Bonechewer Taskmaster",
		23030: "Dragonmaw Sky Stalker",
		23033: "Invisible Stalker (Floating)",
		23047: "Shadowmoon Soldier",
		23049: "Shadowmoon Weapon Master",
		23084: "Black Temple Invis Stalker",
		23089: "Akama",
		23147: "Shadowmoon Grunt",
		23158: "Seer Kanai",
		23159: "Okuno",
		23172: "Hand of Gorefiend",
		23196: "Bonechewer Behemoth",
		23210: "Creature Generator (Akama)",
		23222: "Bonechewer Brawler",
		23223: "Bonechewer Spectator",
		23232: "Mutant War Hound",
		23235: "Bonechewer Blade Fury",
		23236: "Bonechewer Shield Disciple",
		23237: "Bonechewer Blood Prophet",
		23239: "Bonechewer Combatant",
		23288: "Akama Event Stalker",
		23330: "Dragonmaw Wind Reaver",
		23337: "Illidari Centurion",
		23339: "Illidari Heartseeker",
		23374: "Ashtongue Stalker",
		23394: "Promenade Sentinel",
		23397: "Illidari Blood Lord",
		23398: "Angered Soul Fragment",
		23399: "Suffering Soul Fragment",
		23400: "Illidari Archon",
		23401: "Hungering Soul Fragment",
		23402: "Illidari Battle-mage",
		23403: "Illidari Assassin",
		23410: "Spirit of Udalo",
		23411: "Spirit of Olum",
		23412: "Illidan Door Trigger",
		23417: "Reliquary Combat Trigger",
		23421: "Ashtongue Channeler",
		23448: "Glaive Target",
		23472: "World Trigger (Large AOI, Not Immune PC/NPC)",
		23499: "Blood Elf Council Voice Trigger",
		23502: "Reliquary LoS Agro Trigger",
	})
	instances.LoadBosses(hostile, map[uint32]string{
		22841: "Shade of Akama",
		22856: "Reliquary of the Lost",
		22871: "Teron Gorefiend",
		22887: "High Warlord Naj'entus",
		22898: "Supremus",
		22917: "Illidan Stormrage",
		22947: "Mother Shahraz",
		22948: "Gurtogg Bloodboil",
		22949: "Gathios the Shatterer",
		22950: "High Nethermancer Zerevor",
		22951: "Lady Malande",
		22952: "Veras Darkshadow",
		23191: "Akama",
		23426: "The Illidari Council",
	})
	return hostile
}

var BlackTempleFactory = &instances.CommonFactory{
	Name:      "Black Temple",
	ZoneNames: []string{"black temple"},
	MapIDs:    []uint32{564},
	Hostiles:  instances.FromMap(BlackTempleHostiles()),
}

// GruulsLairHostiles returns creature entry IDs for Gruul's Lair (map 565).
func GruulsLairHostiles() map[uint32]instances.Identity {
	hostile := make(map[uint32]instances.Identity)
	instances.LoadAdds(hostile, map[uint32]string{
		19389: "Lair Brute",
		21350: "Gronn-Priest",
	})
	instances.LoadBosses(hostile, map[uint32]string{
		18831: "High King Maulgar",
		18832: "Krosh Firehand",
		18834: "Olm the Summoner",
		18835: "Kiggler the Crazed",
		18836: "Blindeye the Seer",
		19044: "Gruul the Dragonkiller",
	})
	return hostile
}

var GruulsLairFactory = &instances.CommonFactory{
	Name:      "Gruul's Lair",
	ZoneNames: []string{"gruul's lair"},
	MapIDs:    []uint32{565},
	Hostiles:  instances.FromMap(GruulsLairHostiles()),
}

// ZulAmanHostiles returns creature entry IDs for Zul'Aman (map 568).
func ZulAmanHostiles() map[uint32]instances.Identity {
	hostile := make(map[uint32]instances.Identity)
	instances.LoadAdds(hostile, map[uint32]string{
		21252: "World Trigger (Not Immune PC)",
		22515: "World Trigger",
		22517: "World Trigger (Large AOI)",
		23542: "Amani'shi Axe Thrower",
		23580: "Amani'shi Warbringer",
		23581: "Amani'shi Medicine Man",
		23582: "Amani'shi Tribesman",
		23584: "Amani Bear",
		23586: "Amani'shi Scout",
		23596: "Amani'shi Flame Caster",
		23597: "Amani'shi Guardian",
		23746: "Zul'Aman Exterior InvisMan",
		23774: "Amani'shi Trainer",
		23790: "Tanzar",
		23807: "Zul'Aman - Bear God Invisman",
		23813: "Zul'Aman - Dragonhawk God Invisman",
		23814: "Zul'Aman - Eagle God Invisman",
		23815: "Zul'Aman - Lynx God Invisman",
		23817: "Dragonhawk Egg",
		23834: "Amani Dragonhawk",
		23889: "Amani'shi Savage",
		24043: "Amani Lynx",
		24047: "Amani Crocolisk",
		24059: "Amani'shi Beast Tamer",
		24064: "Amani Lynx Cub",
		24065: "Amani'shi Handler",
		24138: "Tamed Amani Crocolisk",
		24175: "Amani'shi Lookout",
		24179: "Amani'shi Wind Walker",
		24180: "Amani'shi Protector",
		24217: "Amani Bear Mount",
		24312: "Dragonhawk Egg",
		24325: "Eagle Troll Spawn Target",
		24363: "Hex Lord Malacrass",
		24374: "Amani'shi Berserker",
		24396: "Forest Frog",
		24444: "Kraz's Corpse",
		24530: "Amani Elder Lynx",
		24549: "Amani'shi Tempest",
		25173: "Zul'Aman Door Trigger",
	})
	instances.LoadBosses(hostile, map[uint32]string{
		23574: "Akil'zon",
		23576: "Nalorakk",
		23577: "Halazzi",
		23578: "Jan'alai",
		23863: "Zul'jin",
		24239: "Hex Lord Malacrass",
	})
	return hostile
}

var ZulAmanFactory = &instances.CommonFactory{
	Name:      "Zul'Aman",
	ZoneNames: []string{"zul'aman"},
	MapIDs:    []uint32{568},
	Hostiles:  instances.FromMap(ZulAmanHostiles()),
}

// SunwellPlateauHostiles returns creature entry IDs for Sunwell Plateau (map 580).
func SunwellPlateauHostiles() map[uint32]instances.Identity {
	hostile := make(map[uint32]instances.Identity)
	instances.LoadAdds(hostile, map[uint32]string{
		19871: "World Trigger (Not Immune NPC)",
		22515: "World Trigger",
		23472: "World Trigger (Large AOI, Not Immune PC/NPC)",
		24928: "Sunwell Daily Bunny x 1.00",
		25357: "Felmyst Flight Target - Left",
		25358: "Felmyst Flight Target - Right",
		25363: "Sunblade Cabalist",
		25367: "Sunblade Arch Mage",
		25368: "Sunblade Slayer",
		25369: "Sunblade Vindicator",
		25370: "Sunblade Dusk Priest",
		25371: "Sunblade Dawn Priest",
		25372: "Sunblade Scout",
		25373: "Shadowsword Soulbinder",
		25483: "Shadowsword Manafiend",
		25484: "Shadowsword Assassin",
		25486: "Shadowsword Vanquisher",
		25506: "Shadowsword Lifeshaper",
		25507: "Sunblade Protector",
		25508: "Shadowsword Guardian",
		25509: "Priestess of Torment",
		25591: "Painbringer",
		25592: "Doomfire Destroyer",
		25593: "Apocalypse Guard",
		25595: "Chaos Gazer",
		25597: "Oblivion Mage",
		25599: "Cataclysm Hound",
		25608: "Kil'jaeden",
		25632: "Vindicator Moorba",
		25638: "Captain Selana",
		25639: "Anchorite Elbadon",
		25644: "Neophyte Narama",
		25661: "Shattered Sun Soldier",
		25770: "M'uru Portal Target",
		25795: "Normal Realm",
		25796: "Spectral Realm",
		25837: "Shadowsword Commander",
		25848: "Gauntlet Imp Trigger",
		25851: "Volatile Fiend",
		25867: "Sunblade Dragonhawk",
		25953: "Fel Crystal Spell Target",
		36991: "Sunwell Guardian",
		37746: "Sunwell Caster Bunny",
		37765: "Captain Auric Sunchaser",
		37781: "Sunwell Honor Guard",
		38047: "Blood Elf Pilgrim",
		38056: "Chamberlain Galiros",
	})
	instances.LoadBosses(hostile, map[uint32]string{
		24850: "Kalecgos",
		24882: "Brutallus",
		24895: "Madrigosa",
		25038: "Felmyst",
		25165: "Lady Sacrolash",
		25166: "Grand Warlock Alythess",
		25741: "M'uru",
		37763: "Grand Magister Rommath",
		37764: "Lor'themar Theron",
	})
	return hostile
}

var SunwellPlateauFactory = &instances.CommonFactory{
	Name:      "Sunwell Plateau",
	ZoneNames: []string{"sunwell plateau"},
	MapIDs:    []uint32{580},
	Hostiles:  instances.FromMap(SunwellPlateauHostiles()),
}
