import type { WoWSpell } from "../src/types.js";

/**
 * Build a minimal WoWSpell for resolver tests. Only the fields the resolver
 * reads need realistic values; everything else gets harmless defaults.
 */
export function makeSpell(overrides: Partial<WoWSpell> = {}): WoWSpell {
  const base: WoWSpell = {
    id: 1,
    name: { "0": "Test Spell" },
    subtext: { "0": "Rank 1" },
    description: { "0": "" },
    aura_description: { "0": "" },
    spell_icon: { ID: 0, TextureFilename: "" },
    active_icon: { ID: 0, TextureFilename: "" },
    spell_level: 1,
    base_level: 1,
    max_level: 1,
    category: {
      ID: 0,
      Flags: 0,
      UsesPerWeek: 0,
      Name: "",
      MaxCharges: 0,
      ChargeRecoveryTime: 0,
      TypeMask: 0,
    },
    school: { value: 0, string: "Physical" },
    spell_class_set: { value: 0, string: "" },
    spell_class_mask: 0,
    power_type: { value: 0, string: "Mana" },
    mana_cost: 0,
    mana_cost_pct: 0,
    mana_cost_per_level: 0,
    mana_per_second: 0,
    reagent: [],
    reagent_count: [],
    casting_time: { ID: 0, Base: 0, PerLevel: 0, Minimum: 0 },
    range: { ID: 0, RangeMin: 0, RangeMax: 0, Flags: 0, Name: "" },
    duration: { ID: 0, Duration: 0, DurationPerLevel: 0, MaxDuration: 0 },
    recovery_time: 0,
    start_recovery_time: 0,
    start_recovery_category: 0,
    category_recovery_time: 0,
    mechanic: { value: 0, string: "None" },
    dispel_type: { value: 0, string: "None" },
    prevention_type: { value: 0, string: "None" },
    defense_type: { value: 0, string: "None" },
    caster_aura_state: { value: 0, string: "None" },
    target_aura_state: { value: 0, string: "None" },
    interrupt_flags: { mask: 0, string: "" },
    aura_interrupt_flags: { mask: 0, string: "" },
    effect: [],
    effect_aura: [],
    effect_base_points: [0, 0, 0],
    effect_die_sides: [0, 0, 0],
    effect_base_dice: [0, 0, 0],
    effect_dice_per_level: [0, 0, 0],
    effect_real_points_per_level: [0, 0, 0],
    effect_aura_period: [0, 0, 0],
    effect_amplitude: [0, 0, 0],
    effect_chain_amplitude: [0, 0, 0],
    effect_chain_targets: [0, 0, 0],
    effect_trigger_spell: [0, 0, 0],
    effect_item_type: [0, 0, 0],
    effect_misc_value: [0, 0, 0],
    effect_mechanic: [0, 0, 0],
    effect_points_per_combo: [0, 0, 0],
    effect_radius: [],
    implicit_target_a: [],
    implicit_target_b: [],
    proc_chance: 0,
    proc_charges: 0,
    proc_type_mask: { mask: 0, string: "" },
    proc_flags: { mask: 0, string: "" },
    targets: { mask: 0, string: "" },
    max_targets: 0,
    max_target_level: 0,
    target_creature_type: { mask: 0, string: "" },
    attributes: { blocks: [], string: "" },
    equipped_item_class: { value: 0, string: "" },
    equipped_item_subclass: 0,
    equipped_item_inv_types: { mask: 0, string: "" },
    speed: 0,
    spell_priority: 0,
    stance_bar_order: 0,
    cumulative_aura: 0,
    modal_next_spell: 0,
    requires_spell_focus: { ID: 0, Name: "" },
    totems_id: 0,
    totem: [],
    cast_ui: 0,
    required_aura_vision: 0,
    min_faction_id: 0,
    min_reputation: 0,
    spell_visual_id: [],
    damage_type: 0,
    attack_outcome: 0,
  };
  return { ...base, ...overrides };
}
