package database

// The LogFormat type, its constants, and helpers (Scan, Valid,
// AllLogFormatValues, NullLogFormat) are generated by sqlc from the `log_format`
// Postgres enum — see database/models.go. This file holds only the hand-written
// LogType -> LogFormat mapping, which has no SQL equivalent.

// Format returns the parse format for a LogType. LogFormat is the parsing axis
// split out of LogType (format vs flavor vs dataset); see TODO_DATASETS.md
// "Log Format / Flavor Split".
//
// Format names encode the client build + the specific logging tool (not the
// game-content flavor), because the same content can run on a different client
// build. The seven historical LogType values collapse onto the four formats:
//
//	v1                                     -> 1.12a-superwow-addon
//	v2, kronos                             -> 1.12a-cc-addon
//	warmane, epoch, azerothcore-clientside -> 3.3.5a-cc-addon
//	azerothcore                            -> azerothcore-mod
//
// This mapping is the runtime source of truth for the collapse and must stay in
// sync with the backfill CASE in migration 000123. Every valid LogType maps to a
// valid LogFormat (guarded by exhaustive tests); an unknown LogType returns the
// empty LogFormat (check with LogFormat.Valid).
func (e LogType) Format() LogFormat {
	switch e {
	case LogTypeV1:
		return LogFormat112aSuperwowAddon
	case LogTypeV2, LogTypeKronos:
		return LogFormat112aCcAddon
	case LogTypeWarmane, LogTypeEpoch, LogTypeAzerothcoreClientside:
		return LogFormat335aCcAddon
	case LogTypeAzerothcore:
		return LogFormatAzerothcoreMod
	}
	return ""
}
