// Code generated by scripts/dbcdata (server: warmane). DO NOT EDIT.

export type DurationModifierRef = {
  spellId: number;
  name: string;
  percent: number;
  flat: number;
  deprecated: boolean;
};

export type AffectedSpell = {
  name: string;
  spellClassSet: number;
  baseDurationMs: number;
  maxDurationMs: number;
  deprecated: boolean;
  modifiers: DurationModifierRef[];
};

// AffectedSpells maps spell IDs to their base duration and
// all passive talents that can modify their duration.
export const AffectedSpells: Record<number, AffectedSpell> = {
  139: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  467: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  770: {
    name: "Faerie Fire",
    spellClassSet: 7,
    baseDurationMs: 300000,
    maxDurationMs: 305000,
    deprecated: false,
    modifiers: [
      { spellId: 24479, name: "Improved Faerie Fire", percent: 0, flat: 5000, deprecated: false },
    ],
  },
  774: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  782: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  853: {
    name: "Hammer of Justice",
    spellClassSet: 10,
    baseDurationMs: 3000,
    maxDurationMs: 3500,
    deprecated: false,
    modifiers: [
      { spellId: 24188, name: "Improved Hammer of Justice", percent: 0, flat: 500, deprecated: false },
    ],
  },
  1002: {
    name: "Eyes of the Beast",
    spellClassSet: 9,
    baseDurationMs: 60000,
    maxDurationMs: 120000,
    deprecated: false,
    modifiers: [
      { spellId: 19557, name: "Improved Eyes of the Beast", percent: 0, flat: 30000, deprecated: false },
      { spellId: 19558, name: "Improved Eyes of the Beast", percent: 0, flat: 60000, deprecated: false },
    ],
  },
  1038: {
    name: "Hand of Salvation",
    spellClassSet: 10,
    baseDurationMs: 10000,
    maxDurationMs: 610000,
    deprecated: false,
    modifiers: [
      { spellId: 20194, name: "Improved Blessing of Salvation", percent: 0, flat: 300000, deprecated: false },
      { spellId: 20195, name: "Improved Blessing of Salvation", percent: 0, flat: 600000, deprecated: false },
    ],
  },
  1058: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  1075: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  1430: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  1776: {
    name: "Gouge",
    spellClassSet: 8,
    baseDurationMs: 4000,
    maxDurationMs: 5500,
    deprecated: false,
    modifiers: [
      { spellId: 13741, name: "Improved Gouge", percent: 0, flat: 500, deprecated: false },
      { spellId: 13792, name: "Improved Gouge", percent: 0, flat: 1500, deprecated: false },
      { spellId: 13793, name: "Improved Gouge", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  1777: {
    name: "Gouge",
    spellClassSet: 8,
    baseDurationMs: 4000,
    maxDurationMs: 5500,
    deprecated: false,
    modifiers: [
      { spellId: 13741, name: "Improved Gouge", percent: 0, flat: 500, deprecated: false },
      { spellId: 13792, name: "Improved Gouge", percent: 0, flat: 1500, deprecated: false },
      { spellId: 13793, name: "Improved Gouge", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  1978: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  2090: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  2091: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  2983: {
    name: "Sprint",
    spellClassSet: 8,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 23049, name: "Sprint Duration Increase", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  3627: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  5143: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 3000,
    maxDurationMs: 4000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  5144: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 4000,
    maxDurationMs: 5000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  5145: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  5246: {
    name: "Intimidating Shout",
    spellClassSet: 4,
    baseDurationMs: 8000,
    maxDurationMs: 10000,
    deprecated: false,
    modifiers: [
      { spellId: 19870, name: "Improved Intimidating Shout", percent: 0, flat: 1000, deprecated: false },
      { spellId: 19871, name: "Improved Intimidating Shout", percent: 0, flat: 2000, deprecated: false },
    ],
  },
  5588: {
    name: "Hammer of Justice",
    spellClassSet: 10,
    baseDurationMs: 4000,
    maxDurationMs: 4500,
    deprecated: false,
    modifiers: [
      { spellId: 24188, name: "Improved Hammer of Justice", percent: 0, flat: 500, deprecated: false },
    ],
  },
  5589: {
    name: "Hammer of Justice",
    spellClassSet: 10,
    baseDurationMs: 5000,
    maxDurationMs: 5500,
    deprecated: false,
    modifiers: [
      { spellId: 24188, name: "Improved Hammer of Justice", percent: 0, flat: 500, deprecated: false },
    ],
  },
  6074: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  6075: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  6076: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  6077: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  6078: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  8056: {
    name: "Frost Shock",
    spellClassSet: 11,
    baseDurationMs: 8000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 24461, name: "Improved Frost Shock", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  8058: {
    name: "Frost Shock",
    spellClassSet: 11,
    baseDurationMs: 8000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 24461, name: "Improved Frost Shock", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  8122: {
    name: "Psychic Scream",
    spellClassSet: 6,
    baseDurationMs: 8000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 23044, name: "Psychic Scream Duration Increase", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  8124: {
    name: "Psychic Scream",
    spellClassSet: 6,
    baseDurationMs: 8000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 23044, name: "Psychic Scream Duration Increase", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  8416: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  8417: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  8629: {
    name: "Gouge",
    spellClassSet: 8,
    baseDurationMs: 4000,
    maxDurationMs: 5500,
    deprecated: false,
    modifiers: [
      { spellId: 13741, name: "Improved Gouge", percent: 0, flat: 500, deprecated: false },
      { spellId: 13792, name: "Improved Gouge", percent: 0, flat: 1500, deprecated: false },
      { spellId: 13793, name: "Improved Gouge", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  8696: {
    name: "Sprint",
    spellClassSet: 8,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 23049, name: "Sprint Duration Increase", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  8910: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  8914: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  9756: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  9839: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  9840: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  9841: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  9910: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  10211: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  10212: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  10308: {
    name: "Hammer of Justice",
    spellClassSet: 10,
    baseDurationMs: 6000,
    maxDurationMs: 6500,
    deprecated: false,
    modifiers: [
      { spellId: 24188, name: "Improved Hammer of Justice", percent: 0, flat: 500, deprecated: false },
    ],
  },
  10472: {
    name: "Frost Shock",
    spellClassSet: 11,
    baseDurationMs: 8000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 24461, name: "Improved Frost Shock", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  10473: {
    name: "Frost Shock",
    spellClassSet: 11,
    baseDurationMs: 8000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 24461, name: "Improved Frost Shock", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  10888: {
    name: "Psychic Scream",
    spellClassSet: 6,
    baseDurationMs: 8000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 23044, name: "Psychic Scream Duration Increase", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  10890: {
    name: "Psychic Scream",
    spellClassSet: 6,
    baseDurationMs: 8000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 23044, name: "Psychic Scream Duration Increase", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  10927: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  10928: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  10929: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  11285: {
    name: "Gouge",
    spellClassSet: 8,
    baseDurationMs: 4000,
    maxDurationMs: 5500,
    deprecated: false,
    modifiers: [
      { spellId: 13741, name: "Improved Gouge", percent: 0, flat: 500, deprecated: false },
      { spellId: 13792, name: "Improved Gouge", percent: 0, flat: 1500, deprecated: false },
      { spellId: 13793, name: "Improved Gouge", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  11286: {
    name: "Gouge",
    spellClassSet: 8,
    baseDurationMs: 4000,
    maxDurationMs: 5500,
    deprecated: false,
    modifiers: [
      { spellId: 13741, name: "Improved Gouge", percent: 0, flat: 500, deprecated: false },
      { spellId: 13792, name: "Improved Gouge", percent: 0, flat: 1500, deprecated: false },
      { spellId: 13793, name: "Improved Gouge", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  11305: {
    name: "Sprint",
    spellClassSet: 8,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 23049, name: "Sprint Duration Increase", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  13549: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  13550: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  13551: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  13552: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  13553: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  13554: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  13555: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  16857: {
    name: "Faerie Fire (Feral)",
    spellClassSet: 7,
    baseDurationMs: 300000,
    maxDurationMs: 305000,
    deprecated: false,
    modifiers: [
      { spellId: 24479, name: "Improved Faerie Fire", percent: 0, flat: 5000, deprecated: false },
    ],
  },
  16877: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  19134: {
    name: "Frightening Shout",
    spellClassSet: 4,
    baseDurationMs: 6000,
    maxDurationMs: 8000,
    deprecated: false,
    modifiers: [
      { spellId: 19870, name: "Improved Intimidating Shout", percent: 0, flat: 1000, deprecated: false },
      { spellId: 19871, name: "Improved Intimidating Shout", percent: 0, flat: 2000, deprecated: false },
    ],
  },
  20184: {
    name: "Judgement of Justice",
    spellClassSet: 10,
    baseDurationMs: 20000,
    maxDurationMs: 24000,
    deprecated: false,
    modifiers: [
      { spellId: 26130, name: "Avenger Judgment Bonus", percent: 20, flat: 0, deprecated: false },
    ],
  },
  20185: {
    name: "Judgement of Light",
    spellClassSet: 10,
    baseDurationMs: 20000,
    maxDurationMs: 24000,
    deprecated: false,
    modifiers: [
      { spellId: 26130, name: "Avenger Judgment Bonus", percent: 20, flat: 0, deprecated: false },
    ],
  },
  20186: {
    name: "Judgement of Wisdom",
    spellClassSet: 10,
    baseDurationMs: 20000,
    maxDurationMs: 24000,
    deprecated: false,
    modifiers: [
      { spellId: 26130, name: "Avenger Judgment Bonus", percent: 20, flat: 0, deprecated: false },
    ],
  },
  20511: {
    name: "Intimidating Shout",
    spellClassSet: 4,
    baseDurationMs: 8000,
    maxDurationMs: 10000,
    deprecated: false,
    modifiers: [
      { spellId: 19870, name: "Improved Intimidating Shout", percent: 0, flat: 1000, deprecated: false },
      { spellId: 19871, name: "Improved Intimidating Shout", percent: 0, flat: 2000, deprecated: false },
    ],
  },
  21183: {
    name: "Heart of the Crusader",
    spellClassSet: 10,
    baseDurationMs: 20000,
    maxDurationMs: 24000,
    deprecated: false,
    modifiers: [
      { spellId: 26130, name: "Avenger Judgment Bonus", percent: 20, flat: 0, deprecated: false },
    ],
  },
  21335: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  21337: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  21869: {
    name: "Repulsive Gaze",
    spellClassSet: 4,
    baseDurationMs: 8000,
    maxDurationMs: 10000,
    deprecated: false,
    modifiers: [
      { spellId: 19870, name: "Improved Intimidating Shout", percent: 0, flat: 1000, deprecated: false },
      { spellId: 19871, name: "Improved Intimidating Shout", percent: 0, flat: 2000, deprecated: false },
    ],
  },
  22128: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  22696: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  22781: {
    name: "Thornling",
    spellClassSet: 7,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  25059: {
    name: "Dmg Shield",
    spellClassSet: 7,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  25221: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  25222: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  25295: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  25299: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  25315: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  25345: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  25464: {
    name: "Frost Shock",
    spellClassSet: 11,
    baseDurationMs: 8000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 24461, name: "Improved Frost Shock", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  25640: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  25777: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  26135: {
    name: "Battlegear of Eternal Justice",
    spellClassSet: 10,
    baseDurationMs: 0,
    maxDurationMs: 0,
    deprecated: false,
    modifiers: [
      { spellId: 26130, name: "Avenger Judgment Bonus", percent: 20, flat: 0, deprecated: false },
    ],
  },
  26666: {
    name: "Dmg Shield2",
    spellClassSet: 7,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  26981: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  26982: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  26992: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  27016: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  27075: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  27606: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  27610: {
    name: "Psychic Scream",
    spellClassSet: 6,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 23044, name: "Psychic Scream Duration Increase", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  29544: {
    name: "Frightening Shout",
    spellClassSet: 4,
    baseDurationMs: 6000,
    maxDurationMs: 8000,
    deprecated: false,
    modifiers: [
      { spellId: 19870, name: "Improved Intimidating Shout", percent: 0, flat: 1000, deprecated: false },
      { spellId: 19871, name: "Improved Intimidating Shout", percent: 0, flat: 2000, deprecated: false },
    ],
  },
  31271: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  31745: {
    name: "Salvation",
    spellClassSet: 10,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 20194, name: "Improved Blessing of Salvation", percent: 0, flat: 300000, deprecated: false },
      { spellId: 20195, name: "Improved Blessing of Salvation", percent: 0, flat: 600000, deprecated: false },
    ],
  },
  31975: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  32125: {
    name: "Medicinal Swamp Moss",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  32740: {
    name: "Spikes",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  33789: {
    name: "Frightening Shout",
    spellClassSet: 4,
    baseDurationMs: 6000,
    maxDurationMs: 8000,
    deprecated: false,
    modifiers: [
      { spellId: 19870, name: "Improved Intimidating Shout", percent: 0, flat: 1000, deprecated: false },
      { spellId: 19871, name: "Improved Intimidating Shout", percent: 0, flat: 2000, deprecated: false },
    ],
  },
  33907: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  33908: {
    name: "Burning Spikes",
    spellClassSet: 7,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  34343: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  34663: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 15000,
    maxDurationMs: 112500,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  35360: {
    name: "Salvation",
    spellClassSet: 10,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 20194, name: "Improved Blessing of Salvation", percent: 0, flat: 300000, deprecated: false },
      { spellId: 20195, name: "Improved Blessing of Salvation", percent: 0, flat: 600000, deprecated: false },
    ],
  },
  35361: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  35511: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  36886: {
    name: "Spiteful Fury",
    spellClassSet: 10,
    baseDurationMs: 8000,
    maxDurationMs: 608000,
    deprecated: false,
    modifiers: [
      { spellId: 20194, name: "Improved Blessing of Salvation", percent: 0, flat: 300000, deprecated: false },
      { spellId: 20195, name: "Improved Blessing of Salvation", percent: 0, flat: 600000, deprecated: false },
    ],
  },
  36984: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  38699: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  38704: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  38764: {
    name: "Gouge",
    spellClassSet: 8,
    baseDurationMs: 4000,
    maxDurationMs: 5500,
    deprecated: false,
    modifiers: [
      { spellId: 13741, name: "Improved Gouge", percent: 0, flat: 500, deprecated: false },
      { spellId: 13792, name: "Improved Gouge", percent: 0, flat: 1500, deprecated: false },
      { spellId: 13793, name: "Improved Gouge", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  38859: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  38914: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  38945: {
    name: "Frightening Shout",
    spellClassSet: 4,
    baseDurationMs: 6000,
    maxDurationMs: 8000,
    deprecated: false,
    modifiers: [
      { spellId: 19870, name: "Improved Intimidating Shout", percent: 0, flat: 1000, deprecated: false },
      { spellId: 19871, name: "Improved Intimidating Shout", percent: 0, flat: 2000, deprecated: false },
    ],
  },
  38946: {
    name: "Frightening Shout",
    spellClassSet: 4,
    baseDurationMs: 6000,
    maxDurationMs: 8000,
    deprecated: false,
    modifiers: [
      { spellId: 19870, name: "Improved Intimidating Shout", percent: 0, flat: 1000, deprecated: false },
      { spellId: 19871, name: "Improved Intimidating Shout", percent: 0, flat: 2000, deprecated: false },
    ],
  },
  39182: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  42843: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  42846: {
    name: "Arcane Missiles",
    spellClassSet: 3,
    baseDurationMs: 5000,
    maxDurationMs: 6000,
    deprecated: false,
    modifiers: [
      { spellId: 21228, name: "Arcane Missiles +1", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  44174: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  46192: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  48067: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  48068: {
    name: "Renew",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  48440: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 12000,
    maxDurationMs: 15000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  48441: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  49000: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  49001: {
    name: "Serpent Sting",
    spellClassSet: 9,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 24467, name: "Improved Serpent Sting", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  49235: {
    name: "Frost Shock",
    spellClassSet: 11,
    baseDurationMs: 8000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 24461, name: "Improved Frost Shock", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  49236: {
    name: "Frost Shock",
    spellClassSet: 11,
    baseDurationMs: 8000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 24461, name: "Improved Frost Shock", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  50412: {
    name: "Copy of Thorns",
    spellClassSet: 7,
    baseDurationMs: 30000,
    maxDurationMs: 135000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  50419: {
    name: "Brambles",
    spellClassSet: 7,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  51439: {
    name: "Backlash",
    spellClassSet: 7,
    baseDurationMs: 6000,
    maxDurationMs: 99000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  51956: {
    name: "Death Pact",
    spellClassSet: 6,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 26171, name: "Increased Renew Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  53307: {
    name: "Thorns",
    spellClassSet: 7,
    baseDurationMs: 600000,
    maxDurationMs: 990000,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  54498: {
    name: "Heart of the Crusader",
    spellClassSet: 10,
    baseDurationMs: 20000,
    maxDurationMs: 24000,
    deprecated: false,
    modifiers: [
      { spellId: 26130, name: "Avenger Judgment Bonus", percent: 20, flat: 0, deprecated: false },
    ],
  },
  54499: {
    name: "Heart of the Crusader",
    spellClassSet: 10,
    baseDurationMs: 20000,
    maxDurationMs: 24000,
    deprecated: false,
    modifiers: [
      { spellId: 26130, name: "Avenger Judgment Bonus", percent: 20, flat: 0, deprecated: false },
    ],
  },
  58154: {
    name: "Hammer of Injustice",
    spellClassSet: 10,
    baseDurationMs: 6000,
    maxDurationMs: 6500,
    deprecated: false,
    modifiers: [
      { spellId: 24188, name: "Improved Hammer of Justice", percent: 0, flat: 500, deprecated: false },
    ],
  },
  60573: {
    name: "LK Arena 4 Gladiator's Totem of Survival",
    spellClassSet: 11,
    baseDurationMs: 0,
    maxDurationMs: 0,
    deprecated: false,
    modifiers: [
      { spellId: 24461, name: "Improved Frost Shock", percent: 0, flat: 1000, deprecated: false },
    ],
  },
  60798: {
    name: "Monkey Speed",
    spellClassSet: 8,
    baseDurationMs: 6000,
    maxDurationMs: 9000,
    deprecated: false,
    modifiers: [
      { spellId: 23049, name: "Sprint Duration Increase", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  61840: {
    name: "Righteous Vengeance",
    spellClassSet: 10,
    baseDurationMs: 8000,
    maxDurationMs: 9600,
    deprecated: false,
    modifiers: [
      { spellId: 26130, name: "Avenger Judgment Bonus", percent: 20, flat: 0, deprecated: false },
    ],
  },
  61922: {
    name: "Sprint",
    spellClassSet: 8,
    baseDurationMs: 15000,
    maxDurationMs: 18000,
    deprecated: false,
    modifiers: [
      { spellId: 23049, name: "Sprint Duration Increase", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  64522: {
    name: "Dmg Shield2",
    spellClassSet: 7,
    baseDurationMs: -1,
    maxDurationMs: -1,
    deprecated: false,
    modifiers: [
      { spellId: 21972, name: "Improved Thorns Duration", percent: 0, flat: 60000, deprecated: false },
      { spellId: 23557, name: "Improved Thorns Damage", percent: 50, flat: 0, deprecated: false },
    ],
  },
  64760: {
    name: "Item - Druid T8 Restoration 4P Bonus",
    spellClassSet: 7,
    baseDurationMs: 0,
    maxDurationMs: 0,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  64801: {
    name: "Rejuvenation",
    spellClassSet: 7,
    baseDurationMs: 0,
    maxDurationMs: 0,
    deprecated: false,
    modifiers: [
      { spellId: 21871, name: "Increased Rejuvenation Duration", percent: 0, flat: 3000, deprecated: false },
    ],
  },
  65930: {
    name: "Intimidating Shout",
    spellClassSet: 4,
    baseDurationMs: 8000,
    maxDurationMs: 10000,
    deprecated: false,
    modifiers: [
      { spellId: 19870, name: "Improved Intimidating Shout", percent: 0, flat: 1000, deprecated: false },
      { spellId: 19871, name: "Improved Intimidating Shout", percent: 0, flat: 2000, deprecated: false },
    ],
  },
  68055: {
    name: "Judgements of the Just",
    spellClassSet: 10,
    baseDurationMs: 20000,
    maxDurationMs: 24000,
    deprecated: false,
    modifiers: [
      { spellId: 26130, name: "Avenger Judgment Bonus", percent: 20, flat: 0, deprecated: false },
    ],
  },
};
