BEGIN;

-- This restores the schema only. Dropped compatibility data cannot be recovered
-- without reimporting the source spell data.
ALTER TABLE dbc_spells
    ADD COLUMN power_type INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN mana_cost INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN mana_cost_pct INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN mana_cost_per_level INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN mana_per_second INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_die_sides_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_real_pts_per_level_0 REAL NOT NULL DEFAULT 0,
    ADD COLUMN effect_base_points_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_mechanic_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_radius_index_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_aura_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_aura_period_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_amplitude_0 REAL NOT NULL DEFAULT 0,
    ADD COLUMN effect_chain_targets_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_item_type_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_misc_value_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_trigger_spell_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_pts_per_combo_0 REAL NOT NULL DEFAULT 0,
    ADD COLUMN effect_base_dice_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_dice_per_level_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_chain_amplitude_0 REAL NOT NULL DEFAULT 0,
    ADD COLUMN implicit_target_a_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN implicit_target_b_0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_die_sides_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_real_pts_per_level_1 REAL NOT NULL DEFAULT 0,
    ADD COLUMN effect_base_points_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_mechanic_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_radius_index_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_aura_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_aura_period_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_amplitude_1 REAL NOT NULL DEFAULT 0,
    ADD COLUMN effect_chain_targets_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_item_type_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_misc_value_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_trigger_spell_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_pts_per_combo_1 REAL NOT NULL DEFAULT 0,
    ADD COLUMN effect_base_dice_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_dice_per_level_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_chain_amplitude_1 REAL NOT NULL DEFAULT 0,
    ADD COLUMN implicit_target_a_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN implicit_target_b_1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_die_sides_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_real_pts_per_level_2 REAL NOT NULL DEFAULT 0,
    ADD COLUMN effect_base_points_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_mechanic_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_radius_index_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_aura_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_aura_period_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_amplitude_2 REAL NOT NULL DEFAULT 0,
    ADD COLUMN effect_chain_targets_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_item_type_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_misc_value_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_trigger_spell_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_pts_per_combo_2 REAL NOT NULL DEFAULT 0,
    ADD COLUMN effect_base_dice_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_dice_per_level_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_chain_amplitude_2 REAL NOT NULL DEFAULT 0,
    ADD COLUMN implicit_target_a_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN implicit_target_b_2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN effect_base_points_f REAL[] NOT NULL DEFAULT '{}';

COMMIT;
