BEGIN;

CREATE TABLE dbc_spell_effects (
    dataset_id UUID NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    spell_id INTEGER NOT NULL,
    difficulty_id INTEGER NOT NULL,
    effect_index INTEGER NOT NULL,
    source_id INTEGER NOT NULL,
    bonus_coefficient_from_ap REAL NOT NULL,
    coefficient REAL NOT NULL,
    effect INTEGER NOT NULL,
    effect_amplitude REAL NOT NULL,
    effect_attributes INTEGER NOT NULL,
    effect_aura INTEGER NOT NULL,
    effect_aura_period INTEGER NOT NULL,
    effect_base_points_f REAL NOT NULL,
    effect_bonus_coefficient REAL NOT NULL,
    effect_chain_amplitude REAL NOT NULL,
    effect_chain_targets INTEGER NOT NULL,
    effect_item_type INTEGER NOT NULL,
    effect_mechanic INTEGER NOT NULL,
    effect_misc_value INTEGER[] NOT NULL,
    effect_points_per_resource REAL NOT NULL,
    effect_pos_facing REAL NOT NULL,
    effect_radius_index INTEGER[] NOT NULL,
    effect_real_points_per_level REAL NOT NULL,
    effect_spell_class_mask INTEGER[] NOT NULL,
    effect_trigger_spell INTEGER NOT NULL,
    group_size_base_points_coefficient REAL NOT NULL,
    node_field_12_0_0_63534_001 INTEGER NOT NULL,
    pvp_multiplier REAL NOT NULL,
    resource_coefficient REAL NOT NULL,
    scaling_class INTEGER NOT NULL,
    implicit_target INTEGER[] NOT NULL,
    variance REAL NOT NULL,
    PRIMARY KEY (dataset_id, spell_id, difficulty_id, effect_index, source_id)
);

CREATE TABLE dbc_spell_powers (
    dataset_id UUID NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    spell_id INTEGER NOT NULL,
    order_index INTEGER NOT NULL,
    source_id INTEGER NOT NULL,
    alt_power_bar_id INTEGER NOT NULL,
    mana_cost INTEGER NOT NULL,
    mana_cost_per_level INTEGER NOT NULL,
    mana_per_second INTEGER NOT NULL,
    optional_cost INTEGER NOT NULL,
    optional_cost_pct REAL NOT NULL,
    power_cost_max_pct REAL NOT NULL,
    power_cost_pct REAL NOT NULL,
    power_display_id INTEGER NOT NULL,
    power_pct_per_second REAL NOT NULL,
    power_type INTEGER NOT NULL,
    required_aura_spell_id INTEGER NOT NULL,
    PRIMARY KEY (dataset_id, spell_id, order_index, source_id)
);

CREATE TABLE dbc_spell_variants (
    dataset_id UUID NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    spell_id INTEGER NOT NULL,
    difficulty_id INTEGER NOT NULL,

    misc_id INTEGER,
    active_icon_file_data_id INTEGER,
    active_spell_visual_script INTEGER,
    attributes INTEGER[],
    casting_time_index INTEGER,
    content_tuning_id INTEGER,
    duration_index INTEGER,
    launch_delay REAL,
    min_duration REAL,
    pvp_duration_index INTEGER,
    range_index INTEGER,
    school_mask INTEGER,
    show_future_spell_player_condition_id INTEGER,
    speed REAL,
    spell_icon_file_data_id INTEGER,
    spell_visual_script INTEGER,

    aura_options_id INTEGER,
    cumulative_aura INTEGER,
    proc_category_recovery INTEGER,
    proc_chance INTEGER,
    proc_charges INTEGER,
    proc_type_mask INTEGER[],
    spell_procs_per_minute_id INTEGER,

    aura_restrictions_id INTEGER,
    caster_aura_spell INTEGER,
    caster_aura_state INTEGER,
    caster_aura_type INTEGER,
    exclude_caster_aura_spell INTEGER,
    exclude_caster_aura_state INTEGER,
    exclude_caster_aura_type INTEGER,
    exclude_target_aura_spell INTEGER,
    exclude_target_aura_state INTEGER,
    exclude_target_aura_type INTEGER,
    target_aura_spell INTEGER,
    target_aura_state INTEGER,
    target_aura_type INTEGER,

    class_options_id INTEGER,
    modal_next_spell INTEGER,
    spell_class_set INTEGER,
    spell_class_mask INTEGER[],

    interrupts_id INTEGER,
    aura_interrupt_flags INTEGER[],
    channel_interrupt_flags INTEGER[],
    interrupt_flags INTEGER,

    categories_id INTEGER,
    category INTEGER,
    charge_category INTEGER,
    defense_type INTEGER,
    diminish_type INTEGER,
    dispel_type INTEGER,
    mechanic INTEGER,
    prevention_type INTEGER,
    start_recovery_category INTEGER,

    cooldowns_id INTEGER,
    aura_spell_id INTEGER,
    category_recovery_time INTEGER,
    recovery_time INTEGER,
    start_recovery_time INTEGER,

    levels_id INTEGER,
    base_level INTEGER,
    max_level INTEGER,
    max_passive_aura_level INTEGER,
    spell_level INTEGER,

    target_restrictions_id INTEGER,
    cone_degrees REAL,
    max_target_level INTEGER,
    max_targets INTEGER,
    target_creature_type INTEGER,
    targets INTEGER,
    width REAL,

    PRIMARY KEY (dataset_id, spell_id, difficulty_id)
);

COMMIT;
