// Code generated by scripts/dbcdata (server: epoch). DO NOT EDIT.

package epoch

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.ExtraAttackSpells = map[int32]dbcmem.ExtraAttackSpell{
		3391: {Name: "Thrash", NumExtraAttacks: 2},
		15494: {Name: "Fury of Forgewright", NumExtraAttacks: 2},
		15601: {Name: "Hand of Justice", NumExtraAttacks: 1},
		15642: {Name: "Ironfoe", NumExtraAttacks: 3},
		16459: {Name: "Sword Specialization", NumExtraAttacks: 1},
		16843: {Name: "Crimson Fury", NumExtraAttacks: 3},
		18797: {Name: "Flurry Axe", NumExtraAttacks: 1},
		19105: {Name: "MHTest01 Effect", NumExtraAttacks: 2},
		19109: {Name: "MHTest02 Effect", NumExtraAttacks: 2},
		21919: {Name: "Thrash", NumExtraAttacks: 1},
		32731: {Name: "Flay", NumExtraAttacks: 2},
		32746: {Name: "Reckoning", NumExtraAttacks: 1},
		32910: {Name: "Windfury", NumExtraAttacks: 2},
		38229: {Name: "Windfury", NumExtraAttacks: 2},
		38308: {Name: "Blinkstrike", NumExtraAttacks: 1},
		59830: {Name: "Battleworn Thrash Blade", NumExtraAttacks: 1},
		65976: {Name: "Windfury", NumExtraAttacks: 2},
		66923: {Name: "Hack and Slash", NumExtraAttacks: 1},
	}
}
