package services

const (
	ServiceLogger      = "logger"
	ServicePrometheus  = "prometheus"
	ServicePProf       = "pprof"
	ServiceStorage     = "storage"
	ServicePGXPool     = "pgxpool"
	ServiceDatabase    = "database"
	ServiceRiverQueue  = "riverqueue"
	ServiceChronicle   = "chronicle"
	ServiceDiscordBot  = "discordbot"
	ServiceAPI         = "api"
	ServiceAPIKey      = "api-key"
	ServiceExternalAPI = "external-api"
	ServiceAuthz       = "authz"
	ServiceWoWDB       = "wow-db"
	ServiceAssets      = "assets"
	ServiceGameData    = "gamedata"
	ServiceMail        = "mail"
	ServiceAccessURL   = "accessurl"
	ServiceRetention   = "retention"
	ServiceTelemetry   = "telemetry"
	ServiceTenant      = "tenant"
	ServiceApplication = "application"
	ServiceRankings    = "rankings"
	ServiceDataset     = "dataset"
	ServiceCache       = "cache"
)
