// Code generated by "stringer -type SpellClassSet -trimprefix=SpellClassSet"; DO NOT EDIT.

package chrondbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpellClassSetGeneric-0]
	_ = x[SpellClassSet1-1]
	_ = x[SpellClassSet2-2]
	_ = x[SpellClassSetMage-3]
	_ = x[SpellClassSetWarrior-4]
	_ = x[SpellClassSetWarlock-5]
	_ = x[SpellClassSetPriest-6]
	_ = x[SpellClassSetDruid-7]
	_ = x[SpellClassSetRogue-8]
	_ = x[SpellClassSetHunter-9]
	_ = x[SpellClassSetPaladin-10]
	_ = x[SpellClassSetShaman-11]
	_ = x[SpellClassSetDeathKnight-15]
}

const (
	_SpellClassSet_name_0 = "Generic12MageWarriorWarlockPriestDruidRogueHunterPaladinShaman"
	_SpellClassSet_name_1 = "DeathKnight"
)

var (
	_SpellClassSet_index_0 = [...]uint8{0, 7, 8, 9, 13, 20, 27, 33, 38, 43, 49, 56, 62}
)

func (i SpellClassSet) String() string {
	switch {
	case 0 <= i && i <= 11:
		return _SpellClassSet_name_0[_SpellClassSet_index_0[i]:_SpellClassSet_index_0[i+1]]
	case i == 15:
		return _SpellClassSet_name_1
	default:
		return "SpellClassSet(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
