syntax = "proto3";

package chronicleproto;

option go_package = "github.com/Emyrk/chronicle/api/chronicleproto";

enum School {
  Unknown = 0;
  None = 1;
  Physical = 2;
  Holy = 3;
  Fire = 4;
  Nature = 5;
  Frost = 6;
  Shadow = 7;
  Arcane = 8;
}

enum CastAction {
  ActionUnknown = 0;
  ActionCasts = 1;
  ActionBeginsToCast = 2;
  ActionChannels = 3;
  ActionFailsCasting = 4;
}

enum AuraApplication {
  ApplicationUnknown = 0;
  ApplicationGains = 1;
  ApplicationFades = 2;
  ApplicationRemoved = 3;
}

enum AuraState {
  StateUnknown = 0;
  StateAdded = 1;
  StateRemoved = 2;
  StateModified = 3;
}

message SpellData {
  int32 id = 1;
  string name = 2;
  uint32 attack_outcome = 3;  // AttackOutcome bitmask of possible hit table results
}

message Tailer {
  optional uint32 amount = 1;
  uint32 hitType = 2;
}

message ActivityEntry {
  string guid = 1;
  string eventType = 2;  // "start", "end", "slain", "bump"
}

message EventMeta {
  int32 index = 1;
  int64 offsetMilli = 2;
  repeated ActivityEntry activity = 3;
}

message Heal {
  EventMeta meta = 1;
  string caster = 3;
  string target = 4;
  string sourceName = 5;
  int32 amount = 6;
  uint32 hitType = 7;
  optional SpellData spellData = 8;
  School school = 9;
}

message Damage {
  EventMeta meta = 1;

  optional string caster = 3;
  // sourceName is the spell or ability name (or environmental source)
  string sourceName = 4;
  string target = 5;
  uint32 hitType = 6;
  int32 amount = 7;
  School school = 8;
  repeated Tailer tailers = 9;
  optional SpellData spellData = 10;
}

message ResourceChange {
  EventMeta meta = 1;
  string target = 3;
  int32 amount = 4;
  string resourceType = 5;
  optional string caster = 6;
  optional string sourceName = 7;
  string direction = 8;
  optional SpellData spellData = 9;
}

message ExtraAttack {
  EventMeta meta = 1;
  string target = 2;
  int32 amount = 3;
  string sourceName = 5;
  optional SpellData spellData = 6;
}

message Slain {
  EventMeta meta = 1;
  string target = 2;
  optional string caster = 3;
  optional Damage attribution = 4;
}

message Spell {
  string name = 1;
  int32 id = 2;
  optional int32 rank = 3;
}

message Cast {
  EventMeta meta = 1;
  string caster = 2;
  CastAction action = 3;
  optional string target = 4;
  Spell spell = 5;
}

message Aura {
  EventMeta meta = 1;
  string target = 2;
  string spellName = 3;
  int32 currentAmount = 4;
  AuraApplication application = 5;
  AuraState state = 6;
  optional SpellData spellData = 7;
  bool isBuff = 8;
}

message AuraCast {
  EventMeta meta = 1;
  SpellData spell = 2;
  string caster = 3;
  optional string target = 4;
  int32 effect = 5;
  int32 amplitude = 6;
  int32 effectMiscValue = 7;
  int32 durationMS = 8;
  int32 capStatus = 9;
  int32 effectAuraName = 10;
}

message SpellGo {
  EventMeta meta = 1;
  optional int32 itemID = 2;
  optional SpellData spellData = 3;
  string caster = 4;
  optional string target = 5;
  int32 numHits = 6;
  int32 numMisses = 7;
  optional string corpseOwner = 8;
  reserved 9; // was spellname
}