// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chronicle.proto

package chronicleproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type School int32

const (
	School_Unknown  School = 0
	School_None     School = 1
	School_Physical School = 2
	School_Holy     School = 3
	School_Fire     School = 4
	School_Nature   School = 5
	School_Frost    School = 6
	School_Shadow   School = 7
	School_Arcane   School = 8
)

// Enum value maps for School.
var (
	School_name = map[int32]string{
		0: "Unknown",
		1: "None",
		2: "Physical",
		3: "Holy",
		4: "Fire",
		5: "Nature",
		6: "Frost",
		7: "Shadow",
		8: "Arcane",
	}
	School_value = map[string]int32{
		"Unknown":  0,
		"None":     1,
		"Physical": 2,
		"Holy":     3,
		"Fire":     4,
		"Nature":   5,
		"Frost":    6,
		"Shadow":   7,
		"Arcane":   8,
	}
)

func (x School) Enum() *School {
	p := new(School)
	*p = x
	return p
}

func (x School) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (School) Descriptor() protoreflect.EnumDescriptor {
	return file_chronicle_proto_enumTypes[0].Descriptor()
}

func (School) Type() protoreflect.EnumType {
	return &file_chronicle_proto_enumTypes[0]
}

func (x School) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use School.Descriptor instead.
func (School) EnumDescriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{0}
}

type CastAction int32

const (
	CastAction_ActionUnknown      CastAction = 0
	CastAction_ActionCasts        CastAction = 1
	CastAction_ActionBeginsToCast CastAction = 2
	CastAction_ActionChannels     CastAction = 3
	CastAction_ActionFailsCasting CastAction = 4
)

// Enum value maps for CastAction.
var (
	CastAction_name = map[int32]string{
		0: "ActionUnknown",
		1: "ActionCasts",
		2: "ActionBeginsToCast",
		3: "ActionChannels",
		4: "ActionFailsCasting",
	}
	CastAction_value = map[string]int32{
		"ActionUnknown":      0,
		"ActionCasts":        1,
		"ActionBeginsToCast": 2,
		"ActionChannels":     3,
		"ActionFailsCasting": 4,
	}
)

func (x CastAction) Enum() *CastAction {
	p := new(CastAction)
	*p = x
	return p
}

func (x CastAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CastAction) Descriptor() protoreflect.EnumDescriptor {
	return file_chronicle_proto_enumTypes[1].Descriptor()
}

func (CastAction) Type() protoreflect.EnumType {
	return &file_chronicle_proto_enumTypes[1]
}

func (x CastAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CastAction.Descriptor instead.
func (CastAction) EnumDescriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{1}
}

type AuraApplication int32

const (
	AuraApplication_ApplicationUnknown AuraApplication = 0
	AuraApplication_ApplicationGains   AuraApplication = 1
	AuraApplication_ApplicationFades   AuraApplication = 2
	AuraApplication_ApplicationRemoved AuraApplication = 3
)

// Enum value maps for AuraApplication.
var (
	AuraApplication_name = map[int32]string{
		0: "ApplicationUnknown",
		1: "ApplicationGains",
		2: "ApplicationFades",
		3: "ApplicationRemoved",
	}
	AuraApplication_value = map[string]int32{
		"ApplicationUnknown": 0,
		"ApplicationGains":   1,
		"ApplicationFades":   2,
		"ApplicationRemoved": 3,
	}
)

func (x AuraApplication) Enum() *AuraApplication {
	p := new(AuraApplication)
	*p = x
	return p
}

func (x AuraApplication) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuraApplication) Descriptor() protoreflect.EnumDescriptor {
	return file_chronicle_proto_enumTypes[2].Descriptor()
}

func (AuraApplication) Type() protoreflect.EnumType {
	return &file_chronicle_proto_enumTypes[2]
}

func (x AuraApplication) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuraApplication.Descriptor instead.
func (AuraApplication) EnumDescriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{2}
}

type AuraState int32

const (
	AuraState_StateUnknown  AuraState = 0
	AuraState_StateAdded    AuraState = 1
	AuraState_StateRemoved  AuraState = 2
	AuraState_StateModified AuraState = 3
)

// Enum value maps for AuraState.
var (
	AuraState_name = map[int32]string{
		0: "StateUnknown",
		1: "StateAdded",
		2: "StateRemoved",
		3: "StateModified",
	}
	AuraState_value = map[string]int32{
		"StateUnknown":  0,
		"StateAdded":    1,
		"StateRemoved":  2,
		"StateModified": 3,
	}
)

func (x AuraState) Enum() *AuraState {
	p := new(AuraState)
	*p = x
	return p
}

func (x AuraState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuraState) Descriptor() protoreflect.EnumDescriptor {
	return file_chronicle_proto_enumTypes[3].Descriptor()
}

func (AuraState) Type() protoreflect.EnumType {
	return &file_chronicle_proto_enumTypes[3]
}

func (x AuraState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuraState.Descriptor instead.
func (AuraState) EnumDescriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{3}
}

type DispelType int32

const (
	DispelType_DispelTypeNone         DispelType = 0
	DispelType_DispelTypeMagic        DispelType = 1
	DispelType_DispelTypeCurse        DispelType = 2
	DispelType_DispelTypeDisease      DispelType = 3
	DispelType_DispelTypePoison       DispelType = 4
	DispelType_DispelTypeStealth      DispelType = 5
	DispelType_DispelTypeInvisibility DispelType = 6
)

// Enum value maps for DispelType.
var (
	DispelType_name = map[int32]string{
		0: "DispelTypeNone",
		1: "DispelTypeMagic",
		2: "DispelTypeCurse",
		3: "DispelTypeDisease",
		4: "DispelTypePoison",
		5: "DispelTypeStealth",
		6: "DispelTypeInvisibility",
	}
	DispelType_value = map[string]int32{
		"DispelTypeNone":         0,
		"DispelTypeMagic":        1,
		"DispelTypeCurse":        2,
		"DispelTypeDisease":      3,
		"DispelTypePoison":       4,
		"DispelTypeStealth":      5,
		"DispelTypeInvisibility": 6,
	}
)

func (x DispelType) Enum() *DispelType {
	p := new(DispelType)
	*p = x
	return p
}

func (x DispelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispelType) Descriptor() protoreflect.EnumDescriptor {
	return file_chronicle_proto_enumTypes[4].Descriptor()
}

func (DispelType) Type() protoreflect.EnumType {
	return &file_chronicle_proto_enumTypes[4]
}

func (x DispelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispelType.Descriptor instead.
func (DispelType) EnumDescriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{4}
}

type SpellData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AttackOutcome uint32                 `protobuf:"varint,3,opt,name=attack_outcome,json=attackOutcome,proto3" json:"attack_outcome,omitempty"` // AttackOutcome bitmask of possible hit table results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpellData) Reset() {
	*x = SpellData{}
	mi := &file_chronicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpellData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellData) ProtoMessage() {}

func (x *SpellData) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellData.ProtoReflect.Descriptor instead.
func (*SpellData) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{0}
}

func (x *SpellData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpellData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpellData) GetAttackOutcome() uint32 {
	if x != nil {
		return x.AttackOutcome
	}
	return 0
}

type Tailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        *uint32                `protobuf:"varint,1,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	HitType       uint32                 `protobuf:"varint,2,opt,name=hitType,proto3" json:"hitType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tailer) Reset() {
	*x = Tailer{}
	mi := &file_chronicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tailer) ProtoMessage() {}

func (x *Tailer) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tailer.ProtoReflect.Descriptor instead.
func (*Tailer) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{1}
}

func (x *Tailer) GetAmount() uint32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *Tailer) GetHitType() uint32 {
	if x != nil {
		return x.HitType
	}
	return 0
}

type ActivityEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=eventType,proto3" json:"eventType,omitempty"` // "start", "end", "slain", "bump"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityEntry) Reset() {
	*x = ActivityEntry{}
	mi := &file_chronicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityEntry) ProtoMessage() {}

func (x *ActivityEntry) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityEntry.ProtoReflect.Descriptor instead.
func (*ActivityEntry) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityEntry) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *ActivityEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type EventMeta struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Index       int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	OffsetMilli int64                  `protobuf:"varint,2,opt,name=offsetMilli,proto3" json:"offsetMilli,omitempty"`
	Activity    []*ActivityEntry       `protobuf:"bytes,3,rep,name=activity,proto3" json:"activity,omitempty"`
	// True when this event was synthetically generated (e.g. projected pre-pull
	// aura), not sourced from the original combat log.
	IsSynthetic   bool `protobuf:"varint,4,opt,name=is_synthetic,json=isSynthetic,proto3" json:"is_synthetic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_chronicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{3}
}

func (x *EventMeta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EventMeta) GetOffsetMilli() int64 {
	if x != nil {
		return x.OffsetMilli
	}
	return 0
}

func (x *EventMeta) GetActivity() []*ActivityEntry {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *EventMeta) GetIsSynthetic() bool {
	if x != nil {
		return x.IsSynthetic
	}
	return false
}

type Heal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster        string                 `protobuf:"bytes,3,opt,name=caster,proto3" json:"caster,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	SourceName    string                 `protobuf:"bytes,5,opt,name=sourceName,proto3" json:"sourceName,omitempty"`
	Amount        int32                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	HitType       uint32                 `protobuf:"varint,7,opt,name=hitType,proto3" json:"hitType,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,8,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	School        School                 `protobuf:"varint,9,opt,name=school,proto3,enum=chronicleproto.School" json:"school,omitempty"`
	Overheal      int32                  `protobuf:"varint,10,opt,name=overheal,proto3" json:"overheal,omitempty"`
	Absorbed      int32                  `protobuf:"varint,11,opt,name=absorbed,proto3" json:"absorbed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heal) Reset() {
	*x = Heal{}
	mi := &file_chronicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heal) ProtoMessage() {}

func (x *Heal) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heal.ProtoReflect.Descriptor instead.
func (*Heal) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{4}
}

func (x *Heal) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Heal) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *Heal) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Heal) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Heal) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Heal) GetHitType() uint32 {
	if x != nil {
		return x.HitType
	}
	return 0
}

func (x *Heal) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

func (x *Heal) GetSchool() School {
	if x != nil {
		return x.School
	}
	return School_Unknown
}

func (x *Heal) GetOverheal() int32 {
	if x != nil {
		return x.Overheal
	}
	return 0
}

func (x *Heal) GetAbsorbed() int32 {
	if x != nil {
		return x.Absorbed
	}
	return 0
}

type Damage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Meta   *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster *string                `protobuf:"bytes,3,opt,name=caster,proto3,oneof" json:"caster,omitempty"`
	// sourceName is the spell or ability name (or environmental source)
	SourceName    string     `protobuf:"bytes,4,opt,name=sourceName,proto3" json:"sourceName,omitempty"`
	Target        string     `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	HitType       uint32     `protobuf:"varint,6,opt,name=hitType,proto3" json:"hitType,omitempty"`
	Amount        int32      `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	School        School     `protobuf:"varint,8,opt,name=school,proto3,enum=chronicleproto.School" json:"school,omitempty"`
	Tailers       []*Tailer  `protobuf:"bytes,9,rep,name=tailers,proto3" json:"tailers,omitempty"`
	SpellData     *SpellData `protobuf:"bytes,10,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	Overkill      int32      `protobuf:"varint,11,opt,name=overkill,proto3" json:"overkill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Damage) Reset() {
	*x = Damage{}
	mi := &file_chronicle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Damage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Damage) ProtoMessage() {}

func (x *Damage) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Damage.ProtoReflect.Descriptor instead.
func (*Damage) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{5}
}

func (x *Damage) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Damage) GetCaster() string {
	if x != nil && x.Caster != nil {
		return *x.Caster
	}
	return ""
}

func (x *Damage) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Damage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Damage) GetHitType() uint32 {
	if x != nil {
		return x.HitType
	}
	return 0
}

func (x *Damage) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Damage) GetSchool() School {
	if x != nil {
		return x.School
	}
	return School_Unknown
}

func (x *Damage) GetTailers() []*Tailer {
	if x != nil {
		return x.Tailers
	}
	return nil
}

func (x *Damage) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

func (x *Damage) GetOverkill() int32 {
	if x != nil {
		return x.Overkill
	}
	return 0
}

type ResourceChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	Caster        *string                `protobuf:"bytes,6,opt,name=caster,proto3,oneof" json:"caster,omitempty"`
	SourceName    *string                `protobuf:"bytes,7,opt,name=sourceName,proto3,oneof" json:"sourceName,omitempty"`
	Direction     string                 `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,9,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	OverResource  int32                  `protobuf:"varint,10,opt,name=overResource,proto3" json:"overResource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceChange) Reset() {
	*x = ResourceChange{}
	mi := &file_chronicle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceChange) ProtoMessage() {}

func (x *ResourceChange) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceChange.ProtoReflect.Descriptor instead.
func (*ResourceChange) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceChange) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ResourceChange) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ResourceChange) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ResourceChange) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceChange) GetCaster() string {
	if x != nil && x.Caster != nil {
		return *x.Caster
	}
	return ""
}

func (x *ResourceChange) GetSourceName() string {
	if x != nil && x.SourceName != nil {
		return *x.SourceName
	}
	return ""
}

func (x *ResourceChange) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ResourceChange) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

func (x *ResourceChange) GetOverResource() int32 {
	if x != nil {
		return x.OverResource
	}
	return 0
}

type ExtraAttack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	SourceName    string                 `protobuf:"bytes,5,opt,name=sourceName,proto3" json:"sourceName,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,6,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraAttack) Reset() {
	*x = ExtraAttack{}
	mi := &file_chronicle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraAttack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraAttack) ProtoMessage() {}

func (x *ExtraAttack) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraAttack.ProtoReflect.Descriptor instead.
func (*ExtraAttack) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{7}
}

func (x *ExtraAttack) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ExtraAttack) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ExtraAttack) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExtraAttack) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *ExtraAttack) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

type Slain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Caster        *string                `protobuf:"bytes,3,opt,name=caster,proto3,oneof" json:"caster,omitempty"`
	Attribution   *Damage                `protobuf:"bytes,4,opt,name=attribution,proto3,oneof" json:"attribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slain) Reset() {
	*x = Slain{}
	mi := &file_chronicle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slain) ProtoMessage() {}

func (x *Slain) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slain.ProtoReflect.Descriptor instead.
func (*Slain) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{8}
}

func (x *Slain) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Slain) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Slain) GetCaster() string {
	if x != nil && x.Caster != nil {
		return *x.Caster
	}
	return ""
}

func (x *Slain) GetAttribution() *Damage {
	if x != nil {
		return x.Attribution
	}
	return nil
}

type Resurrection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Spell         *SpellData             `protobuf:"bytes,4,opt,name=spell,proto3" json:"spell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resurrection) Reset() {
	*x = Resurrection{}
	mi := &file_chronicle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resurrection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resurrection) ProtoMessage() {}

func (x *Resurrection) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resurrection.ProtoReflect.Descriptor instead.
func (*Resurrection) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{9}
}

func (x *Resurrection) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Resurrection) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Resurrection) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Resurrection) GetSpell() *SpellData {
	if x != nil {
		return x.Spell
	}
	return nil
}

type Spell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Rank          *int32                 `protobuf:"varint,3,opt,name=rank,proto3,oneof" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spell) Reset() {
	*x = Spell{}
	mi := &file_chronicle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spell) ProtoMessage() {}

func (x *Spell) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spell.ProtoReflect.Descriptor instead.
func (*Spell) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{10}
}

func (x *Spell) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spell) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Spell) GetRank() int32 {
	if x != nil && x.Rank != nil {
		return *x.Rank
	}
	return 0
}

type Cast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster        string                 `protobuf:"bytes,2,opt,name=caster,proto3" json:"caster,omitempty"`
	Action        CastAction             `protobuf:"varint,3,opt,name=action,proto3,enum=chronicleproto.CastAction" json:"action,omitempty"`
	Target        *string                `protobuf:"bytes,4,opt,name=target,proto3,oneof" json:"target,omitempty"`
	Spell         *Spell                 `protobuf:"bytes,5,opt,name=spell,proto3" json:"spell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cast) Reset() {
	*x = Cast{}
	mi := &file_chronicle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cast) ProtoMessage() {}

func (x *Cast) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cast.ProtoReflect.Descriptor instead.
func (*Cast) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{11}
}

func (x *Cast) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Cast) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *Cast) GetAction() CastAction {
	if x != nil {
		return x.Action
	}
	return CastAction_ActionUnknown
}

func (x *Cast) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *Cast) GetSpell() *Spell {
	if x != nil {
		return x.Spell
	}
	return nil
}

type Aura struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	SpellName     string                 `protobuf:"bytes,3,opt,name=spellName,proto3" json:"spellName,omitempty"`
	CurrentAmount int32                  `protobuf:"varint,4,opt,name=currentAmount,proto3" json:"currentAmount,omitempty"`
	Application   AuraApplication        `protobuf:"varint,5,opt,name=application,proto3,enum=chronicleproto.AuraApplication" json:"application,omitempty"`
	State         AuraState              `protobuf:"varint,6,opt,name=state,proto3,enum=chronicleproto.AuraState" json:"state,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,7,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	IsBuff        bool                   `protobuf:"varint,8,opt,name=isBuff,proto3" json:"isBuff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aura) Reset() {
	*x = Aura{}
	mi := &file_chronicle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aura) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aura) ProtoMessage() {}

func (x *Aura) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aura.ProtoReflect.Descriptor instead.
func (*Aura) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{12}
}

func (x *Aura) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Aura) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Aura) GetSpellName() string {
	if x != nil {
		return x.SpellName
	}
	return ""
}

func (x *Aura) GetCurrentAmount() int32 {
	if x != nil {
		return x.CurrentAmount
	}
	return 0
}

func (x *Aura) GetApplication() AuraApplication {
	if x != nil {
		return x.Application
	}
	return AuraApplication_ApplicationUnknown
}

func (x *Aura) GetState() AuraState {
	if x != nil {
		return x.State
	}
	return AuraState_StateUnknown
}

func (x *Aura) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

func (x *Aura) GetIsBuff() bool {
	if x != nil {
		return x.IsBuff
	}
	return false
}

type AuraCast struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Spell           *SpellData             `protobuf:"bytes,2,opt,name=spell,proto3" json:"spell,omitempty"`
	Caster          string                 `protobuf:"bytes,3,opt,name=caster,proto3" json:"caster,omitempty"`
	Target          *string                `protobuf:"bytes,4,opt,name=target,proto3,oneof" json:"target,omitempty"`
	Effect          int32                  `protobuf:"varint,5,opt,name=effect,proto3" json:"effect,omitempty"`
	Amplitude       int32                  `protobuf:"varint,6,opt,name=amplitude,proto3" json:"amplitude,omitempty"`
	EffectMiscValue int32                  `protobuf:"varint,7,opt,name=effectMiscValue,proto3" json:"effectMiscValue,omitempty"`
	DurationMS      int32                  `protobuf:"varint,8,opt,name=durationMS,proto3" json:"durationMS,omitempty"`
	CapStatus       int32                  `protobuf:"varint,9,opt,name=capStatus,proto3" json:"capStatus,omitempty"`
	EffectAuraName  int32                  `protobuf:"varint,10,opt,name=effectAuraName,proto3" json:"effectAuraName,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuraCast) Reset() {
	*x = AuraCast{}
	mi := &file_chronicle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuraCast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuraCast) ProtoMessage() {}

func (x *AuraCast) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuraCast.ProtoReflect.Descriptor instead.
func (*AuraCast) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{13}
}

func (x *AuraCast) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AuraCast) GetSpell() *SpellData {
	if x != nil {
		return x.Spell
	}
	return nil
}

func (x *AuraCast) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *AuraCast) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *AuraCast) GetEffect() int32 {
	if x != nil {
		return x.Effect
	}
	return 0
}

func (x *AuraCast) GetAmplitude() int32 {
	if x != nil {
		return x.Amplitude
	}
	return 0
}

func (x *AuraCast) GetEffectMiscValue() int32 {
	if x != nil {
		return x.EffectMiscValue
	}
	return 0
}

func (x *AuraCast) GetDurationMS() int32 {
	if x != nil {
		return x.DurationMS
	}
	return 0
}

func (x *AuraCast) GetCapStatus() int32 {
	if x != nil {
		return x.CapStatus
	}
	return 0
}

func (x *AuraCast) GetEffectAuraName() int32 {
	if x != nil {
		return x.EffectAuraName
	}
	return 0
}

type SpellGo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ItemID        *int32                 `protobuf:"varint,2,opt,name=itemID,proto3,oneof" json:"itemID,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,3,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	Caster        string                 `protobuf:"bytes,4,opt,name=caster,proto3" json:"caster,omitempty"`
	Target        *string                `protobuf:"bytes,5,opt,name=target,proto3,oneof" json:"target,omitempty"`
	NumHits       int32                  `protobuf:"varint,6,opt,name=numHits,proto3" json:"numHits,omitempty"`
	NumMisses     int32                  `protobuf:"varint,7,opt,name=numMisses,proto3" json:"numMisses,omitempty"`
	CorpseOwner   *string                `protobuf:"bytes,8,opt,name=corpseOwner,proto3,oneof" json:"corpseOwner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpellGo) Reset() {
	*x = SpellGo{}
	mi := &file_chronicle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpellGo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellGo) ProtoMessage() {}

func (x *SpellGo) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellGo.ProtoReflect.Descriptor instead.
func (*SpellGo) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{14}
}

func (x *SpellGo) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SpellGo) GetItemID() int32 {
	if x != nil && x.ItemID != nil {
		return *x.ItemID
	}
	return 0
}

func (x *SpellGo) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

func (x *SpellGo) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *SpellGo) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *SpellGo) GetNumHits() int32 {
	if x != nil {
		return x.NumHits
	}
	return 0
}

func (x *SpellGo) GetNumMisses() int32 {
	if x != nil {
		return x.NumMisses
	}
	return 0
}

func (x *SpellGo) GetCorpseOwner() string {
	if x != nil && x.CorpseOwner != nil {
		return *x.CorpseOwner
	}
	return ""
}

type SpellStart struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Meta             *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ItemID           *int32                 `protobuf:"varint,2,opt,name=itemID,proto3,oneof" json:"itemID,omitempty"`
	SpellData        *SpellData             `protobuf:"bytes,3,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	Caster           string                 `protobuf:"bytes,4,opt,name=caster,proto3" json:"caster,omitempty"`
	Target           *string                `protobuf:"bytes,5,opt,name=target,proto3,oneof" json:"target,omitempty"`
	CastFlags        int32                  `protobuf:"varint,6,opt,name=castFlags,proto3" json:"castFlags,omitempty"`
	CastTimeMilli    int32                  `protobuf:"varint,7,opt,name=castTimeMilli,proto3" json:"castTimeMilli,omitempty"`
	ChannelTimeMilli int32                  `protobuf:"varint,8,opt,name=channelTimeMilli,proto3" json:"channelTimeMilli,omitempty"`
	SpellType        int32                  `protobuf:"varint,9,opt,name=spellType,proto3" json:"spellType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SpellStart) Reset() {
	*x = SpellStart{}
	mi := &file_chronicle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpellStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellStart) ProtoMessage() {}

func (x *SpellStart) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellStart.ProtoReflect.Descriptor instead.
func (*SpellStart) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{15}
}

func (x *SpellStart) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SpellStart) GetItemID() int32 {
	if x != nil && x.ItemID != nil {
		return *x.ItemID
	}
	return 0
}

func (x *SpellStart) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

func (x *SpellStart) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *SpellStart) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *SpellStart) GetCastFlags() int32 {
	if x != nil {
		return x.CastFlags
	}
	return 0
}

func (x *SpellStart) GetCastTimeMilli() int32 {
	if x != nil {
		return x.CastTimeMilli
	}
	return 0
}

func (x *SpellStart) GetChannelTimeMilli() int32 {
	if x != nil {
		return x.ChannelTimeMilli
	}
	return 0
}

func (x *SpellStart) GetSpellType() int32 {
	if x != nil {
		return x.SpellType
	}
	return 0
}

type SpellFail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster        string                 `protobuf:"bytes,2,opt,name=caster,proto3" json:"caster,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,3,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	FailedBySever bool                   `protobuf:"varint,4,opt,name=failedBySever,proto3" json:"failedBySever,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpellFail) Reset() {
	*x = SpellFail{}
	mi := &file_chronicle_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpellFail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellFail) ProtoMessage() {}

func (x *SpellFail) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellFail.ProtoReflect.Descriptor instead.
func (*SpellFail) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{16}
}

func (x *SpellFail) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SpellFail) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *SpellFail) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

func (x *SpellFail) GetFailedBySever() bool {
	if x != nil {
		return x.FailedBySever
	}
	return false
}

type UnitClassification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	UnitType      int32                  `protobuf:"varint,3,opt,name=unitType,proto3" json:"unitType,omitempty"`
	Affiliation   int32                  `protobuf:"varint,4,opt,name=affiliation,proto3" json:"affiliation,omitempty"`
	Owner         *string                `protobuf:"bytes,5,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Controller    *string                `protobuf:"bytes,6,opt,name=controller,proto3,oneof" json:"controller,omitempty"`
	SpellId       int32                  `protobuf:"varint,7,opt,name=spellId,proto3" json:"spellId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitClassification) Reset() {
	*x = UnitClassification{}
	mi := &file_chronicle_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitClassification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitClassification) ProtoMessage() {}

func (x *UnitClassification) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitClassification.ProtoReflect.Descriptor instead.
func (*UnitClassification) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{17}
}

func (x *UnitClassification) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *UnitClassification) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UnitClassification) GetUnitType() int32 {
	if x != nil {
		return x.UnitType
	}
	return 0
}

func (x *UnitClassification) GetAffiliation() int32 {
	if x != nil {
		return x.Affiliation
	}
	return 0
}

func (x *UnitClassification) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *UnitClassification) GetController() string {
	if x != nil && x.Controller != nil {
		return *x.Controller
	}
	return ""
}

func (x *UnitClassification) GetSpellId() int32 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

type Dispel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster        string                 `protobuf:"bytes,2,opt,name=caster,proto3" json:"caster,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,4,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	DispelType    DispelType             `protobuf:"varint,5,opt,name=dispelType,proto3,enum=chronicleproto.DispelType" json:"dispelType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dispel) Reset() {
	*x = Dispel{}
	mi := &file_chronicle_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dispel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dispel) ProtoMessage() {}

func (x *Dispel) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dispel.ProtoReflect.Descriptor instead.
func (*Dispel) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{18}
}

func (x *Dispel) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Dispel) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *Dispel) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Dispel) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

func (x *Dispel) GetDispelType() DispelType {
	if x != nil {
		return x.DispelType
	}
	return DispelType_DispelTypeNone
}

type CombatantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Guid          string                 `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	HeroClass     string                 `protobuf:"bytes,4,opt,name=heroClass,proto3" json:"heroClass,omitempty"`
	Race          string                 `protobuf:"bytes,5,opt,name=race,proto3" json:"race,omitempty"`
	Gender        int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	GuildName     *string                `protobuf:"bytes,7,opt,name=guildName,proto3,oneof" json:"guildName,omitempty"`
	Gear          []*CombatantGearSlot   `protobuf:"bytes,8,rep,name=gear,proto3" json:"gear,omitempty"`
	Talents       *CombatantTalents      `protobuf:"bytes,9,opt,name=talents,proto3,oneof" json:"talents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatantInfo) Reset() {
	*x = CombatantInfo{}
	mi := &file_chronicle_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatantInfo) ProtoMessage() {}

func (x *CombatantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatantInfo.ProtoReflect.Descriptor instead.
func (*CombatantInfo) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{19}
}

func (x *CombatantInfo) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CombatantInfo) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *CombatantInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CombatantInfo) GetHeroClass() string {
	if x != nil {
		return x.HeroClass
	}
	return ""
}

func (x *CombatantInfo) GetRace() string {
	if x != nil {
		return x.Race
	}
	return ""
}

func (x *CombatantInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CombatantInfo) GetGuildName() string {
	if x != nil && x.GuildName != nil {
		return *x.GuildName
	}
	return ""
}

func (x *CombatantInfo) GetGear() []*CombatantGearSlot {
	if x != nil {
		return x.Gear
	}
	return nil
}

func (x *CombatantInfo) GetTalents() *CombatantTalents {
	if x != nil {
		return x.Talents
	}
	return nil
}

type Interrupt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster        string                 `protobuf:"bytes,2,opt,name=caster,proto3" json:"caster,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	SpellName     string                 `protobuf:"bytes,4,opt,name=spell_name,json=spellName,proto3" json:"spell_name,omitempty"`                                   // name of interrupted spell
	ExtraSpellId  int32                  `protobuf:"varint,5,opt,name=extra_spell_id,json=extraSpellId,proto3" json:"extra_spell_id,omitempty"`                       // ID of interrupted spell
	ExtraSchool   School                 `protobuf:"varint,6,opt,name=extra_school,json=extraSchool,proto3,enum=chronicleproto.School" json:"extra_school,omitempty"` // school of interrupted spell
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interrupt) Reset() {
	*x = Interrupt{}
	mi := &file_chronicle_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interrupt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interrupt) ProtoMessage() {}

func (x *Interrupt) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interrupt.ProtoReflect.Descriptor instead.
func (*Interrupt) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{20}
}

func (x *Interrupt) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Interrupt) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *Interrupt) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Interrupt) GetSpellName() string {
	if x != nil {
		return x.SpellName
	}
	return ""
}

func (x *Interrupt) GetExtraSpellId() int32 {
	if x != nil {
		return x.ExtraSpellId
	}
	return 0
}

func (x *Interrupt) GetExtraSchool() School {
	if x != nil {
		return x.ExtraSchool
	}
	return School_Unknown
}

type Absorbed struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Attacker        string                 `protobuf:"bytes,2,opt,name=attacker,proto3" json:"attacker,omitempty"`
	Target          string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	DamageSpellData *SpellData             `protobuf:"bytes,4,opt,name=damageSpellData,proto3,oneof" json:"damageSpellData,omitempty"` // nil for melee (swing) damage
	Caster          string                 `protobuf:"bytes,5,opt,name=caster,proto3" json:"caster,omitempty"`
	AbsorbSpellData *SpellData             `protobuf:"bytes,6,opt,name=absorbSpellData,proto3,oneof" json:"absorbSpellData,omitempty"`
	AbsorbSchool    School                 `protobuf:"varint,7,opt,name=absorbSchool,proto3,enum=chronicleproto.School" json:"absorbSchool,omitempty"`
	Amount          int32                  `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	// estimated is true when the absorb attribution was synthetically inferred
	// from aura tracking heuristics rather than reported by the server (e.g.
	// vanilla 1.12 logs). AzerothCore events leave this false.
	Estimated     bool `protobuf:"varint,9,opt,name=estimated,proto3" json:"estimated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Absorbed) Reset() {
	*x = Absorbed{}
	mi := &file_chronicle_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Absorbed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Absorbed) ProtoMessage() {}

func (x *Absorbed) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Absorbed.ProtoReflect.Descriptor instead.
func (*Absorbed) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{21}
}

func (x *Absorbed) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Absorbed) GetAttacker() string {
	if x != nil {
		return x.Attacker
	}
	return ""
}

func (x *Absorbed) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Absorbed) GetDamageSpellData() *SpellData {
	if x != nil {
		return x.DamageSpellData
	}
	return nil
}

func (x *Absorbed) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *Absorbed) GetAbsorbSpellData() *SpellData {
	if x != nil {
		return x.AbsorbSpellData
	}
	return nil
}

func (x *Absorbed) GetAbsorbSchool() School {
	if x != nil {
		return x.AbsorbSchool
	}
	return School_Unknown
}

func (x *Absorbed) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Absorbed) GetEstimated() bool {
	if x != nil {
		return x.Estimated
	}
	return false
}

type CombatantGearSlot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ItemId             int32                  `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	EnchantId          *int32                 `protobuf:"varint,2,opt,name=enchantId,proto3,oneof" json:"enchantId,omitempty"`
	TemporaryEnchantId *int32                 `protobuf:"varint,3,opt,name=temporaryEnchantId,proto3,oneof" json:"temporaryEnchantId,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CombatantGearSlot) Reset() {
	*x = CombatantGearSlot{}
	mi := &file_chronicle_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatantGearSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatantGearSlot) ProtoMessage() {}

func (x *CombatantGearSlot) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatantGearSlot.ProtoReflect.Descriptor instead.
func (*CombatantGearSlot) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{22}
}

func (x *CombatantGearSlot) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CombatantGearSlot) GetEnchantId() int32 {
	if x != nil && x.EnchantId != nil {
		return *x.EnchantId
	}
	return 0
}

func (x *CombatantGearSlot) GetTemporaryEnchantId() int32 {
	if x != nil && x.TemporaryEnchantId != nil {
		return *x.TemporaryEnchantId
	}
	return 0
}

type CombatantTalents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       []int32                `protobuf:"varint,1,rep,packed,name=summary,proto3" json:"summary,omitempty"` // [3] points per tree
	Trees         []string               `protobuf:"bytes,2,rep,name=trees,proto3" json:"trees,omitempty"`             // [3] rank digit strings, one per tree tab
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatantTalents) Reset() {
	*x = CombatantTalents{}
	mi := &file_chronicle_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatantTalents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatantTalents) ProtoMessage() {}

func (x *CombatantTalents) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatantTalents.ProtoReflect.Descriptor instead.
func (*CombatantTalents) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{23}
}

func (x *CombatantTalents) GetSummary() []int32 {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *CombatantTalents) GetTrees() []string {
	if x != nil {
		return x.Trees
	}
	return nil
}

// CompanionStats carries relay health diagnostics from the
// ChronicleCompanionWoTLK addon. Each bucket is the number of message chunks
// that landed in a one-minute window (index 0 = current minute).
type CompanionStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Dirty         int32                  `protobuf:"varint,2,opt,name=dirty,proto3" json:"dirty,omitempty"`            // total pending (unsent) segments across all providers
	Buckets       []int32                `protobuf:"varint,3,rep,packed,name=buckets,proto3" json:"buckets,omitempty"` // [10] landed chunk counts per minute
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanionStats) Reset() {
	*x = CompanionStats{}
	mi := &file_chronicle_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanionStats) ProtoMessage() {}

func (x *CompanionStats) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanionStats.ProtoReflect.Descriptor instead.
func (*CompanionStats) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{24}
}

func (x *CompanionStats) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CompanionStats) GetDirty() int32 {
	if x != nil {
		return x.Dirty
	}
	return 0
}

func (x *CompanionStats) GetBuckets() []int32 {
	if x != nil {
		return x.Buckets
	}
	return nil
}

var File_chronicle_proto protoreflect.FileDescriptor

const file_chronicle_proto_rawDesc = "" +
	"\n" +
	"\x0fchronicle.proto\x12\x0echronicleproto\"V\n" +
	"\tSpellData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eattack_outcome\x18\x03 \x01(\rR\rattackOutcome\"J\n" +
	"\x06Tailer\x12\x1b\n" +
	"\x06amount\x18\x01 \x01(\rH\x00R\x06amount\x88\x01\x01\x12\x18\n" +
	"\ahitType\x18\x02 \x01(\rR\ahitTypeB\t\n" +
	"\a_amount\"A\n" +
	"\rActivityEntry\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x1c\n" +
	"\teventType\x18\x02 \x01(\tR\teventType\"\xa1\x01\n" +
	"\tEventMeta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12 \n" +
	"\voffsetMilli\x18\x02 \x01(\x03R\voffsetMilli\x129\n" +
	"\bactivity\x18\x03 \x03(\v2\x1d.chronicleproto.ActivityEntryR\bactivity\x12!\n" +
	"\fis_synthetic\x18\x04 \x01(\bR\visSynthetic\"\xeb\x02\n" +
	"\x04Heal\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06caster\x18\x03 \x01(\tR\x06caster\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1e\n" +
	"\n" +
	"sourceName\x18\x05 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x05R\x06amount\x12\x18\n" +
	"\ahitType\x18\a \x01(\rR\ahitType\x12<\n" +
	"\tspellData\x18\b \x01(\v2\x19.chronicleproto.SpellDataH\x00R\tspellData\x88\x01\x01\x12.\n" +
	"\x06school\x18\t \x01(\x0e2\x16.chronicleproto.SchoolR\x06school\x12\x1a\n" +
	"\boverheal\x18\n" +
	" \x01(\x05R\boverheal\x12\x1a\n" +
	"\babsorbed\x18\v \x01(\x05R\babsorbedB\f\n" +
	"\n" +
	"_spellData\"\x93\x03\n" +
	"\x06Damage\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x1b\n" +
	"\x06caster\x18\x03 \x01(\tH\x00R\x06caster\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"sourceName\x18\x04 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x18\n" +
	"\ahitType\x18\x06 \x01(\rR\ahitType\x12\x16\n" +
	"\x06amount\x18\a \x01(\x05R\x06amount\x12.\n" +
	"\x06school\x18\b \x01(\x0e2\x16.chronicleproto.SchoolR\x06school\x120\n" +
	"\atailers\x18\t \x03(\v2\x16.chronicleproto.TailerR\atailers\x12<\n" +
	"\tspellData\x18\n" +
	" \x01(\v2\x19.chronicleproto.SpellDataH\x01R\tspellData\x88\x01\x01\x12\x1a\n" +
	"\boverkill\x18\v \x01(\x05R\boverkillB\t\n" +
	"\a_casterB\f\n" +
	"\n" +
	"_spellData\"\xfd\x02\n" +
	"\x0eResourceChange\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12\"\n" +
	"\fresourceType\x18\x05 \x01(\tR\fresourceType\x12\x1b\n" +
	"\x06caster\x18\x06 \x01(\tH\x00R\x06caster\x88\x01\x01\x12#\n" +
	"\n" +
	"sourceName\x18\a \x01(\tH\x01R\n" +
	"sourceName\x88\x01\x01\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirection\x12<\n" +
	"\tspellData\x18\t \x01(\v2\x19.chronicleproto.SpellDataH\x02R\tspellData\x88\x01\x01\x12\"\n" +
	"\foverResource\x18\n" +
	" \x01(\x05R\foverResourceB\t\n" +
	"\a_casterB\r\n" +
	"\v_sourceNameB\f\n" +
	"\n" +
	"_spellData\"\xd8\x01\n" +
	"\vExtraAttack\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x1e\n" +
	"\n" +
	"sourceName\x18\x05 \x01(\tR\n" +
	"sourceName\x12<\n" +
	"\tspellData\x18\x06 \x01(\v2\x19.chronicleproto.SpellDataH\x00R\tspellData\x88\x01\x01B\f\n" +
	"\n" +
	"_spellData\"\xc5\x01\n" +
	"\x05Slain\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1b\n" +
	"\x06caster\x18\x03 \x01(\tH\x00R\x06caster\x88\x01\x01\x12=\n" +
	"\vattribution\x18\x04 \x01(\v2\x16.chronicleproto.DamageH\x01R\vattribution\x88\x01\x01B\t\n" +
	"\a_casterB\x0e\n" +
	"\f_attribution\"\x9e\x01\n" +
	"\fResurrection\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12/\n" +
	"\x05spell\x18\x04 \x01(\v2\x19.chronicleproto.SpellDataR\x05spell\"M\n" +
	"\x05Spell\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x17\n" +
	"\x04rank\x18\x03 \x01(\x05H\x00R\x04rank\x88\x01\x01B\a\n" +
	"\x05_rank\"\xd6\x01\n" +
	"\x04Cast\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06caster\x18\x02 \x01(\tR\x06caster\x122\n" +
	"\x06action\x18\x03 \x01(\x0e2\x1a.chronicleproto.CastActionR\x06action\x12\x1b\n" +
	"\x06target\x18\x04 \x01(\tH\x00R\x06target\x88\x01\x01\x12+\n" +
	"\x05spell\x18\x05 \x01(\v2\x15.chronicleproto.SpellR\x05spellB\t\n" +
	"\a_target\"\xe9\x02\n" +
	"\x04Aura\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1c\n" +
	"\tspellName\x18\x03 \x01(\tR\tspellName\x12$\n" +
	"\rcurrentAmount\x18\x04 \x01(\x05R\rcurrentAmount\x12A\n" +
	"\vapplication\x18\x05 \x01(\x0e2\x1f.chronicleproto.AuraApplicationR\vapplication\x12/\n" +
	"\x05state\x18\x06 \x01(\x0e2\x19.chronicleproto.AuraStateR\x05state\x12<\n" +
	"\tspellData\x18\a \x01(\v2\x19.chronicleproto.SpellDataH\x00R\tspellData\x88\x01\x01\x12\x16\n" +
	"\x06isBuff\x18\b \x01(\bR\x06isBuffB\f\n" +
	"\n" +
	"_spellData\"\xf0\x02\n" +
	"\bAuraCast\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12/\n" +
	"\x05spell\x18\x02 \x01(\v2\x19.chronicleproto.SpellDataR\x05spell\x12\x16\n" +
	"\x06caster\x18\x03 \x01(\tR\x06caster\x12\x1b\n" +
	"\x06target\x18\x04 \x01(\tH\x00R\x06target\x88\x01\x01\x12\x16\n" +
	"\x06effect\x18\x05 \x01(\x05R\x06effect\x12\x1c\n" +
	"\tamplitude\x18\x06 \x01(\x05R\tamplitude\x12(\n" +
	"\x0feffectMiscValue\x18\a \x01(\x05R\x0feffectMiscValue\x12\x1e\n" +
	"\n" +
	"durationMS\x18\b \x01(\x05R\n" +
	"durationMS\x12\x1c\n" +
	"\tcapStatus\x18\t \x01(\x05R\tcapStatus\x12&\n" +
	"\x0eeffectAuraName\x18\n" +
	" \x01(\x05R\x0eeffectAuraNameB\t\n" +
	"\a_target\"\xe1\x02\n" +
	"\aSpellGo\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x1b\n" +
	"\x06itemID\x18\x02 \x01(\x05H\x00R\x06itemID\x88\x01\x01\x12<\n" +
	"\tspellData\x18\x03 \x01(\v2\x19.chronicleproto.SpellDataH\x01R\tspellData\x88\x01\x01\x12\x16\n" +
	"\x06caster\x18\x04 \x01(\tR\x06caster\x12\x1b\n" +
	"\x06target\x18\x05 \x01(\tH\x02R\x06target\x88\x01\x01\x12\x18\n" +
	"\anumHits\x18\x06 \x01(\x05R\anumHits\x12\x1c\n" +
	"\tnumMisses\x18\a \x01(\x05R\tnumMisses\x12%\n" +
	"\vcorpseOwner\x18\b \x01(\tH\x03R\vcorpseOwner\x88\x01\x01B\t\n" +
	"\a_itemIDB\f\n" +
	"\n" +
	"_spellDataB\t\n" +
	"\a_targetB\x0e\n" +
	"\f_corpseOwnerJ\x04\b\t\x10\n" +
	"\"\xfd\x02\n" +
	"\n" +
	"SpellStart\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x1b\n" +
	"\x06itemID\x18\x02 \x01(\x05H\x00R\x06itemID\x88\x01\x01\x12<\n" +
	"\tspellData\x18\x03 \x01(\v2\x19.chronicleproto.SpellDataH\x01R\tspellData\x88\x01\x01\x12\x16\n" +
	"\x06caster\x18\x04 \x01(\tR\x06caster\x12\x1b\n" +
	"\x06target\x18\x05 \x01(\tH\x02R\x06target\x88\x01\x01\x12\x1c\n" +
	"\tcastFlags\x18\x06 \x01(\x05R\tcastFlags\x12$\n" +
	"\rcastTimeMilli\x18\a \x01(\x05R\rcastTimeMilli\x12*\n" +
	"\x10channelTimeMilli\x18\b \x01(\x05R\x10channelTimeMilli\x12\x1c\n" +
	"\tspellType\x18\t \x01(\x05R\tspellTypeB\t\n" +
	"\a_itemIDB\f\n" +
	"\n" +
	"_spellDataB\t\n" +
	"\a_target\"\xc4\x01\n" +
	"\tSpellFail\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06caster\x18\x02 \x01(\tR\x06caster\x12<\n" +
	"\tspellData\x18\x03 \x01(\v2\x19.chronicleproto.SpellDataH\x00R\tspellData\x88\x01\x01\x12$\n" +
	"\rfailedBySever\x18\x04 \x01(\bR\rfailedBySeverB\f\n" +
	"\n" +
	"_spellData\"\x8c\x02\n" +
	"\x12UnitClassification\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1a\n" +
	"\bunitType\x18\x03 \x01(\x05R\bunitType\x12 \n" +
	"\vaffiliation\x18\x04 \x01(\x05R\vaffiliation\x12\x19\n" +
	"\x05owner\x18\x05 \x01(\tH\x00R\x05owner\x88\x01\x01\x12#\n" +
	"\n" +
	"controller\x18\x06 \x01(\tH\x01R\n" +
	"controller\x88\x01\x01\x12\x18\n" +
	"\aspellId\x18\a \x01(\x05R\aspellIdB\b\n" +
	"\x06_ownerB\r\n" +
	"\v_controller\"\xef\x01\n" +
	"\x06Dispel\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06caster\x18\x02 \x01(\tR\x06caster\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12<\n" +
	"\tspellData\x18\x04 \x01(\v2\x19.chronicleproto.SpellDataH\x00R\tspellData\x88\x01\x01\x12:\n" +
	"\n" +
	"dispelType\x18\x05 \x01(\x0e2\x1a.chronicleproto.DispelTypeR\n" +
	"dispelTypeB\f\n" +
	"\n" +
	"_spellData\"\xe5\x02\n" +
	"\rCombatantInfo\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x12\n" +
	"\x04guid\x18\x02 \x01(\tR\x04guid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\theroClass\x18\x04 \x01(\tR\theroClass\x12\x12\n" +
	"\x04race\x18\x05 \x01(\tR\x04race\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12!\n" +
	"\tguildName\x18\a \x01(\tH\x00R\tguildName\x88\x01\x01\x125\n" +
	"\x04gear\x18\b \x03(\v2!.chronicleproto.CombatantGearSlotR\x04gear\x12?\n" +
	"\atalents\x18\t \x01(\v2 .chronicleproto.CombatantTalentsH\x01R\atalents\x88\x01\x01B\f\n" +
	"\n" +
	"_guildNameB\n" +
	"\n" +
	"\b_talents\"\xea\x01\n" +
	"\tInterrupt\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06caster\x18\x02 \x01(\tR\x06caster\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1d\n" +
	"\n" +
	"spell_name\x18\x04 \x01(\tR\tspellName\x12$\n" +
	"\x0eextra_spell_id\x18\x05 \x01(\x05R\fextraSpellId\x129\n" +
	"\fextra_school\x18\x06 \x01(\x0e2\x16.chronicleproto.SchoolR\vextraSchool\"\xb3\x03\n" +
	"\bAbsorbed\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x1a\n" +
	"\battacker\x18\x02 \x01(\tR\battacker\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12H\n" +
	"\x0fdamageSpellData\x18\x04 \x01(\v2\x19.chronicleproto.SpellDataH\x00R\x0fdamageSpellData\x88\x01\x01\x12\x16\n" +
	"\x06caster\x18\x05 \x01(\tR\x06caster\x12H\n" +
	"\x0fabsorbSpellData\x18\x06 \x01(\v2\x19.chronicleproto.SpellDataH\x01R\x0fabsorbSpellData\x88\x01\x01\x12:\n" +
	"\fabsorbSchool\x18\a \x01(\x0e2\x16.chronicleproto.SchoolR\fabsorbSchool\x12\x16\n" +
	"\x06amount\x18\b \x01(\x05R\x06amount\x12\x1c\n" +
	"\testimated\x18\t \x01(\bR\testimatedB\x12\n" +
	"\x10_damageSpellDataB\x12\n" +
	"\x10_absorbSpellData\"\xa8\x01\n" +
	"\x11CombatantGearSlot\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x05R\x06itemId\x12!\n" +
	"\tenchantId\x18\x02 \x01(\x05H\x00R\tenchantId\x88\x01\x01\x123\n" +
	"\x12temporaryEnchantId\x18\x03 \x01(\x05H\x01R\x12temporaryEnchantId\x88\x01\x01B\f\n" +
	"\n" +
	"_enchantIdB\x15\n" +
	"\x13_temporaryEnchantId\"B\n" +
	"\x10CombatantTalents\x12\x18\n" +
	"\asummary\x18\x01 \x03(\x05R\asummary\x12\x14\n" +
	"\x05trees\x18\x02 \x03(\tR\x05trees\"o\n" +
	"\x0eCompanionStats\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x14\n" +
	"\x05dirty\x18\x02 \x01(\x05R\x05dirty\x12\x18\n" +
	"\abuckets\x18\x03 \x03(\x05R\abuckets*p\n" +
	"\x06School\x12\v\n" +
	"\aUnknown\x10\x00\x12\b\n" +
	"\x04None\x10\x01\x12\f\n" +
	"\bPhysical\x10\x02\x12\b\n" +
	"\x04Holy\x10\x03\x12\b\n" +
	"\x04Fire\x10\x04\x12\n" +
	"\n" +
	"\x06Nature\x10\x05\x12\t\n" +
	"\x05Frost\x10\x06\x12\n" +
	"\n" +
	"\x06Shadow\x10\a\x12\n" +
	"\n" +
	"\x06Arcane\x10\b*t\n" +
	"\n" +
	"CastAction\x12\x11\n" +
	"\rActionUnknown\x10\x00\x12\x0f\n" +
	"\vActionCasts\x10\x01\x12\x16\n" +
	"\x12ActionBeginsToCast\x10\x02\x12\x12\n" +
	"\x0eActionChannels\x10\x03\x12\x16\n" +
	"\x12ActionFailsCasting\x10\x04*m\n" +
	"\x0fAuraApplication\x12\x16\n" +
	"\x12ApplicationUnknown\x10\x00\x12\x14\n" +
	"\x10ApplicationGains\x10\x01\x12\x14\n" +
	"\x10ApplicationFades\x10\x02\x12\x16\n" +
	"\x12ApplicationRemoved\x10\x03*R\n" +
	"\tAuraState\x12\x10\n" +
	"\fStateUnknown\x10\x00\x12\x0e\n" +
	"\n" +
	"StateAdded\x10\x01\x12\x10\n" +
	"\fStateRemoved\x10\x02\x12\x11\n" +
	"\rStateModified\x10\x03*\xaa\x01\n" +
	"\n" +
	"DispelType\x12\x12\n" +
	"\x0eDispelTypeNone\x10\x00\x12\x13\n" +
	"\x0fDispelTypeMagic\x10\x01\x12\x13\n" +
	"\x0fDispelTypeCurse\x10\x02\x12\x15\n" +
	"\x11DispelTypeDisease\x10\x03\x12\x14\n" +
	"\x10DispelTypePoison\x10\x04\x12\x15\n" +
	"\x11DispelTypeStealth\x10\x05\x12\x1a\n" +
	"\x16DispelTypeInvisibility\x10\x06B/Z-github.com/Emyrk/chronicle/api/chronicleprotob\x06proto3"

var (
	file_chronicle_proto_rawDescOnce sync.Once
	file_chronicle_proto_rawDescData []byte
)

func file_chronicle_proto_rawDescGZIP() []byte {
	file_chronicle_proto_rawDescOnce.Do(func() {
		file_chronicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chronicle_proto_rawDesc), len(file_chronicle_proto_rawDesc)))
	})
	return file_chronicle_proto_rawDescData
}

var file_chronicle_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_chronicle_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_chronicle_proto_goTypes = []any{
	(School)(0),                // 0: chronicleproto.School
	(CastAction)(0),            // 1: chronicleproto.CastAction
	(AuraApplication)(0),       // 2: chronicleproto.AuraApplication
	(AuraState)(0),             // 3: chronicleproto.AuraState
	(DispelType)(0),            // 4: chronicleproto.DispelType
	(*SpellData)(nil),          // 5: chronicleproto.SpellData
	(*Tailer)(nil),             // 6: chronicleproto.Tailer
	(*ActivityEntry)(nil),      // 7: chronicleproto.ActivityEntry
	(*EventMeta)(nil),          // 8: chronicleproto.EventMeta
	(*Heal)(nil),               // 9: chronicleproto.Heal
	(*Damage)(nil),             // 10: chronicleproto.Damage
	(*ResourceChange)(nil),     // 11: chronicleproto.ResourceChange
	(*ExtraAttack)(nil),        // 12: chronicleproto.ExtraAttack
	(*Slain)(nil),              // 13: chronicleproto.Slain
	(*Resurrection)(nil),       // 14: chronicleproto.Resurrection
	(*Spell)(nil),              // 15: chronicleproto.Spell
	(*Cast)(nil),               // 16: chronicleproto.Cast
	(*Aura)(nil),               // 17: chronicleproto.Aura
	(*AuraCast)(nil),           // 18: chronicleproto.AuraCast
	(*SpellGo)(nil),            // 19: chronicleproto.SpellGo
	(*SpellStart)(nil),         // 20: chronicleproto.SpellStart
	(*SpellFail)(nil),          // 21: chronicleproto.SpellFail
	(*UnitClassification)(nil), // 22: chronicleproto.UnitClassification
	(*Dispel)(nil),             // 23: chronicleproto.Dispel
	(*CombatantInfo)(nil),      // 24: chronicleproto.CombatantInfo
	(*Interrupt)(nil),          // 25: chronicleproto.Interrupt
	(*Absorbed)(nil),           // 26: chronicleproto.Absorbed
	(*CombatantGearSlot)(nil),  // 27: chronicleproto.CombatantGearSlot
	(*CombatantTalents)(nil),   // 28: chronicleproto.CombatantTalents
	(*CompanionStats)(nil),     // 29: chronicleproto.CompanionStats
}
var file_chronicle_proto_depIdxs = []int32{
	7,  // 0: chronicleproto.EventMeta.activity:type_name -> chronicleproto.ActivityEntry
	8,  // 1: chronicleproto.Heal.meta:type_name -> chronicleproto.EventMeta
	5,  // 2: chronicleproto.Heal.spellData:type_name -> chronicleproto.SpellData
	0,  // 3: chronicleproto.Heal.school:type_name -> chronicleproto.School
	8,  // 4: chronicleproto.Damage.meta:type_name -> chronicleproto.EventMeta
	0,  // 5: chronicleproto.Damage.school:type_name -> chronicleproto.School
	6,  // 6: chronicleproto.Damage.tailers:type_name -> chronicleproto.Tailer
	5,  // 7: chronicleproto.Damage.spellData:type_name -> chronicleproto.SpellData
	8,  // 8: chronicleproto.ResourceChange.meta:type_name -> chronicleproto.EventMeta
	5,  // 9: chronicleproto.ResourceChange.spellData:type_name -> chronicleproto.SpellData
	8,  // 10: chronicleproto.ExtraAttack.meta:type_name -> chronicleproto.EventMeta
	5,  // 11: chronicleproto.ExtraAttack.spellData:type_name -> chronicleproto.SpellData
	8,  // 12: chronicleproto.Slain.meta:type_name -> chronicleproto.EventMeta
	10, // 13: chronicleproto.Slain.attribution:type_name -> chronicleproto.Damage
	8,  // 14: chronicleproto.Resurrection.meta:type_name -> chronicleproto.EventMeta
	5,  // 15: chronicleproto.Resurrection.spell:type_name -> chronicleproto.SpellData
	8,  // 16: chronicleproto.Cast.meta:type_name -> chronicleproto.EventMeta
	1,  // 17: chronicleproto.Cast.action:type_name -> chronicleproto.CastAction
	15, // 18: chronicleproto.Cast.spell:type_name -> chronicleproto.Spell
	8,  // 19: chronicleproto.Aura.meta:type_name -> chronicleproto.EventMeta
	2,  // 20: chronicleproto.Aura.application:type_name -> chronicleproto.AuraApplication
	3,  // 21: chronicleproto.Aura.state:type_name -> chronicleproto.AuraState
	5,  // 22: chronicleproto.Aura.spellData:type_name -> chronicleproto.SpellData
	8,  // 23: chronicleproto.AuraCast.meta:type_name -> chronicleproto.EventMeta
	5,  // 24: chronicleproto.AuraCast.spell:type_name -> chronicleproto.SpellData
	8,  // 25: chronicleproto.SpellGo.meta:type_name -> chronicleproto.EventMeta
	5,  // 26: chronicleproto.SpellGo.spellData:type_name -> chronicleproto.SpellData
	8,  // 27: chronicleproto.SpellStart.meta:type_name -> chronicleproto.EventMeta
	5,  // 28: chronicleproto.SpellStart.spellData:type_name -> chronicleproto.SpellData
	8,  // 29: chronicleproto.SpellFail.meta:type_name -> chronicleproto.EventMeta
	5,  // 30: chronicleproto.SpellFail.spellData:type_name -> chronicleproto.SpellData
	8,  // 31: chronicleproto.UnitClassification.meta:type_name -> chronicleproto.EventMeta
	8,  // 32: chronicleproto.Dispel.meta:type_name -> chronicleproto.EventMeta
	5,  // 33: chronicleproto.Dispel.spellData:type_name -> chronicleproto.SpellData
	4,  // 34: chronicleproto.Dispel.dispelType:type_name -> chronicleproto.DispelType
	8,  // 35: chronicleproto.CombatantInfo.meta:type_name -> chronicleproto.EventMeta
	27, // 36: chronicleproto.CombatantInfo.gear:type_name -> chronicleproto.CombatantGearSlot
	28, // 37: chronicleproto.CombatantInfo.talents:type_name -> chronicleproto.CombatantTalents
	8,  // 38: chronicleproto.Interrupt.meta:type_name -> chronicleproto.EventMeta
	0,  // 39: chronicleproto.Interrupt.extra_school:type_name -> chronicleproto.School
	8,  // 40: chronicleproto.Absorbed.meta:type_name -> chronicleproto.EventMeta
	5,  // 41: chronicleproto.Absorbed.damageSpellData:type_name -> chronicleproto.SpellData
	5,  // 42: chronicleproto.Absorbed.absorbSpellData:type_name -> chronicleproto.SpellData
	0,  // 43: chronicleproto.Absorbed.absorbSchool:type_name -> chronicleproto.School
	8,  // 44: chronicleproto.CompanionStats.meta:type_name -> chronicleproto.EventMeta
	45, // [45:45] is the sub-list for method output_type
	45, // [45:45] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_chronicle_proto_init() }
func file_chronicle_proto_init() {
	if File_chronicle_proto != nil {
		return
	}
	file_chronicle_proto_msgTypes[1].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[4].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[5].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[6].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[7].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[8].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[10].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[11].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[12].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[13].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[14].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[15].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[16].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[17].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[18].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[19].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[21].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chronicle_proto_rawDesc), len(file_chronicle_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chronicle_proto_goTypes,
		DependencyIndexes: file_chronicle_proto_depIdxs,
		EnumInfos:         file_chronicle_proto_enumTypes,
		MessageInfos:      file_chronicle_proto_msgTypes,
	}.Build()
	File_chronicle_proto = out.File
	file_chronicle_proto_goTypes = nil
	file_chronicle_proto_depIdxs = nil
}
