// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chronicle.proto

package chronicleproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type School int32

const (
	School_Unknown  School = 0
	School_None     School = 1
	School_Physical School = 2
	School_Holy     School = 3
	School_Fire     School = 4
	School_Nature   School = 5
	School_Frost    School = 6
	School_Shadow   School = 7
	School_Arcane   School = 8
)

// Enum value maps for School.
var (
	School_name = map[int32]string{
		0: "Unknown",
		1: "None",
		2: "Physical",
		3: "Holy",
		4: "Fire",
		5: "Nature",
		6: "Frost",
		7: "Shadow",
		8: "Arcane",
	}
	School_value = map[string]int32{
		"Unknown":  0,
		"None":     1,
		"Physical": 2,
		"Holy":     3,
		"Fire":     4,
		"Nature":   5,
		"Frost":    6,
		"Shadow":   7,
		"Arcane":   8,
	}
)

func (x School) Enum() *School {
	p := new(School)
	*p = x
	return p
}

func (x School) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (School) Descriptor() protoreflect.EnumDescriptor {
	return file_chronicle_proto_enumTypes[0].Descriptor()
}

func (School) Type() protoreflect.EnumType {
	return &file_chronicle_proto_enumTypes[0]
}

func (x School) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use School.Descriptor instead.
func (School) EnumDescriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{0}
}

type CastAction int32

const (
	CastAction_ActionUnknown      CastAction = 0
	CastAction_ActionCasts        CastAction = 1
	CastAction_ActionBeginsToCast CastAction = 2
	CastAction_ActionChannels     CastAction = 3
	CastAction_ActionFailsCasting CastAction = 4
)

// Enum value maps for CastAction.
var (
	CastAction_name = map[int32]string{
		0: "ActionUnknown",
		1: "ActionCasts",
		2: "ActionBeginsToCast",
		3: "ActionChannels",
		4: "ActionFailsCasting",
	}
	CastAction_value = map[string]int32{
		"ActionUnknown":      0,
		"ActionCasts":        1,
		"ActionBeginsToCast": 2,
		"ActionChannels":     3,
		"ActionFailsCasting": 4,
	}
)

func (x CastAction) Enum() *CastAction {
	p := new(CastAction)
	*p = x
	return p
}

func (x CastAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CastAction) Descriptor() protoreflect.EnumDescriptor {
	return file_chronicle_proto_enumTypes[1].Descriptor()
}

func (CastAction) Type() protoreflect.EnumType {
	return &file_chronicle_proto_enumTypes[1]
}

func (x CastAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CastAction.Descriptor instead.
func (CastAction) EnumDescriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{1}
}

type AuraApplication int32

const (
	AuraApplication_ApplicationUnknown AuraApplication = 0
	AuraApplication_ApplicationGains   AuraApplication = 1
	AuraApplication_ApplicationFades   AuraApplication = 2
	AuraApplication_ApplicationRemoved AuraApplication = 3
)

// Enum value maps for AuraApplication.
var (
	AuraApplication_name = map[int32]string{
		0: "ApplicationUnknown",
		1: "ApplicationGains",
		2: "ApplicationFades",
		3: "ApplicationRemoved",
	}
	AuraApplication_value = map[string]int32{
		"ApplicationUnknown": 0,
		"ApplicationGains":   1,
		"ApplicationFades":   2,
		"ApplicationRemoved": 3,
	}
)

func (x AuraApplication) Enum() *AuraApplication {
	p := new(AuraApplication)
	*p = x
	return p
}

func (x AuraApplication) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuraApplication) Descriptor() protoreflect.EnumDescriptor {
	return file_chronicle_proto_enumTypes[2].Descriptor()
}

func (AuraApplication) Type() protoreflect.EnumType {
	return &file_chronicle_proto_enumTypes[2]
}

func (x AuraApplication) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuraApplication.Descriptor instead.
func (AuraApplication) EnumDescriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{2}
}

type AuraState int32

const (
	AuraState_StateUnknown  AuraState = 0
	AuraState_StateAdded    AuraState = 1
	AuraState_StateRemoved  AuraState = 2
	AuraState_StateModified AuraState = 3
)

// Enum value maps for AuraState.
var (
	AuraState_name = map[int32]string{
		0: "StateUnknown",
		1: "StateAdded",
		2: "StateRemoved",
		3: "StateModified",
	}
	AuraState_value = map[string]int32{
		"StateUnknown":  0,
		"StateAdded":    1,
		"StateRemoved":  2,
		"StateModified": 3,
	}
)

func (x AuraState) Enum() *AuraState {
	p := new(AuraState)
	*p = x
	return p
}

func (x AuraState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuraState) Descriptor() protoreflect.EnumDescriptor {
	return file_chronicle_proto_enumTypes[3].Descriptor()
}

func (AuraState) Type() protoreflect.EnumType {
	return &file_chronicle_proto_enumTypes[3]
}

func (x AuraState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuraState.Descriptor instead.
func (AuraState) EnumDescriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{3}
}

type SpellData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AttackOutcome uint32                 `protobuf:"varint,3,opt,name=attack_outcome,json=attackOutcome,proto3" json:"attack_outcome,omitempty"` // AttackOutcome bitmask of possible hit table results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpellData) Reset() {
	*x = SpellData{}
	mi := &file_chronicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpellData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellData) ProtoMessage() {}

func (x *SpellData) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellData.ProtoReflect.Descriptor instead.
func (*SpellData) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{0}
}

func (x *SpellData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpellData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpellData) GetAttackOutcome() uint32 {
	if x != nil {
		return x.AttackOutcome
	}
	return 0
}

type Tailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        *uint32                `protobuf:"varint,1,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	HitType       uint32                 `protobuf:"varint,2,opt,name=hitType,proto3" json:"hitType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tailer) Reset() {
	*x = Tailer{}
	mi := &file_chronicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tailer) ProtoMessage() {}

func (x *Tailer) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tailer.ProtoReflect.Descriptor instead.
func (*Tailer) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{1}
}

func (x *Tailer) GetAmount() uint32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *Tailer) GetHitType() uint32 {
	if x != nil {
		return x.HitType
	}
	return 0
}

type ActivityEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=eventType,proto3" json:"eventType,omitempty"` // "start", "end", "slain", "bump"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityEntry) Reset() {
	*x = ActivityEntry{}
	mi := &file_chronicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityEntry) ProtoMessage() {}

func (x *ActivityEntry) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityEntry.ProtoReflect.Descriptor instead.
func (*ActivityEntry) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityEntry) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *ActivityEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type EventMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	OffsetMilli   int64                  `protobuf:"varint,2,opt,name=offsetMilli,proto3" json:"offsetMilli,omitempty"`
	Activity      []*ActivityEntry       `protobuf:"bytes,3,rep,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_chronicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{3}
}

func (x *EventMeta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EventMeta) GetOffsetMilli() int64 {
	if x != nil {
		return x.OffsetMilli
	}
	return 0
}

func (x *EventMeta) GetActivity() []*ActivityEntry {
	if x != nil {
		return x.Activity
	}
	return nil
}

type Heal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster        string                 `protobuf:"bytes,3,opt,name=caster,proto3" json:"caster,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	SourceName    string                 `protobuf:"bytes,5,opt,name=sourceName,proto3" json:"sourceName,omitempty"`
	Amount        int32                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	HitType       uint32                 `protobuf:"varint,7,opt,name=hitType,proto3" json:"hitType,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,8,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	School        School                 `protobuf:"varint,9,opt,name=school,proto3,enum=chronicleproto.School" json:"school,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heal) Reset() {
	*x = Heal{}
	mi := &file_chronicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heal) ProtoMessage() {}

func (x *Heal) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heal.ProtoReflect.Descriptor instead.
func (*Heal) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{4}
}

func (x *Heal) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Heal) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *Heal) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Heal) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Heal) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Heal) GetHitType() uint32 {
	if x != nil {
		return x.HitType
	}
	return 0
}

func (x *Heal) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

func (x *Heal) GetSchool() School {
	if x != nil {
		return x.School
	}
	return School_Unknown
}

type Damage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Meta   *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster *string                `protobuf:"bytes,3,opt,name=caster,proto3,oneof" json:"caster,omitempty"`
	// sourceName is the spell or ability name (or environmental source)
	SourceName    string     `protobuf:"bytes,4,opt,name=sourceName,proto3" json:"sourceName,omitempty"`
	Target        string     `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	HitType       uint32     `protobuf:"varint,6,opt,name=hitType,proto3" json:"hitType,omitempty"`
	Amount        int32      `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	School        School     `protobuf:"varint,8,opt,name=school,proto3,enum=chronicleproto.School" json:"school,omitempty"`
	Tailers       []*Tailer  `protobuf:"bytes,9,rep,name=tailers,proto3" json:"tailers,omitempty"`
	SpellData     *SpellData `protobuf:"bytes,10,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Damage) Reset() {
	*x = Damage{}
	mi := &file_chronicle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Damage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Damage) ProtoMessage() {}

func (x *Damage) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Damage.ProtoReflect.Descriptor instead.
func (*Damage) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{5}
}

func (x *Damage) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Damage) GetCaster() string {
	if x != nil && x.Caster != nil {
		return *x.Caster
	}
	return ""
}

func (x *Damage) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Damage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Damage) GetHitType() uint32 {
	if x != nil {
		return x.HitType
	}
	return 0
}

func (x *Damage) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Damage) GetSchool() School {
	if x != nil {
		return x.School
	}
	return School_Unknown
}

func (x *Damage) GetTailers() []*Tailer {
	if x != nil {
		return x.Tailers
	}
	return nil
}

func (x *Damage) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

type ResourceChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	Caster        *string                `protobuf:"bytes,6,opt,name=caster,proto3,oneof" json:"caster,omitempty"`
	SourceName    *string                `protobuf:"bytes,7,opt,name=sourceName,proto3,oneof" json:"sourceName,omitempty"`
	Direction     string                 `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,9,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceChange) Reset() {
	*x = ResourceChange{}
	mi := &file_chronicle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceChange) ProtoMessage() {}

func (x *ResourceChange) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceChange.ProtoReflect.Descriptor instead.
func (*ResourceChange) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceChange) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ResourceChange) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ResourceChange) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ResourceChange) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceChange) GetCaster() string {
	if x != nil && x.Caster != nil {
		return *x.Caster
	}
	return ""
}

func (x *ResourceChange) GetSourceName() string {
	if x != nil && x.SourceName != nil {
		return *x.SourceName
	}
	return ""
}

func (x *ResourceChange) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ResourceChange) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

type ExtraAttack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	SourceName    string                 `protobuf:"bytes,5,opt,name=sourceName,proto3" json:"sourceName,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,6,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraAttack) Reset() {
	*x = ExtraAttack{}
	mi := &file_chronicle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraAttack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraAttack) ProtoMessage() {}

func (x *ExtraAttack) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraAttack.ProtoReflect.Descriptor instead.
func (*ExtraAttack) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{7}
}

func (x *ExtraAttack) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ExtraAttack) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ExtraAttack) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExtraAttack) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *ExtraAttack) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

type Slain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Caster        *string                `protobuf:"bytes,3,opt,name=caster,proto3,oneof" json:"caster,omitempty"`
	Attribution   *Damage                `protobuf:"bytes,4,opt,name=attribution,proto3,oneof" json:"attribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slain) Reset() {
	*x = Slain{}
	mi := &file_chronicle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slain) ProtoMessage() {}

func (x *Slain) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slain.ProtoReflect.Descriptor instead.
func (*Slain) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{8}
}

func (x *Slain) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Slain) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Slain) GetCaster() string {
	if x != nil && x.Caster != nil {
		return *x.Caster
	}
	return ""
}

func (x *Slain) GetAttribution() *Damage {
	if x != nil {
		return x.Attribution
	}
	return nil
}

type Spell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Rank          *int32                 `protobuf:"varint,3,opt,name=rank,proto3,oneof" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spell) Reset() {
	*x = Spell{}
	mi := &file_chronicle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spell) ProtoMessage() {}

func (x *Spell) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spell.ProtoReflect.Descriptor instead.
func (*Spell) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{9}
}

func (x *Spell) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spell) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Spell) GetRank() int32 {
	if x != nil && x.Rank != nil {
		return *x.Rank
	}
	return 0
}

type Cast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Caster        string                 `protobuf:"bytes,2,opt,name=caster,proto3" json:"caster,omitempty"`
	Action        CastAction             `protobuf:"varint,3,opt,name=action,proto3,enum=chronicleproto.CastAction" json:"action,omitempty"`
	Target        *string                `protobuf:"bytes,4,opt,name=target,proto3,oneof" json:"target,omitempty"`
	Spell         *Spell                 `protobuf:"bytes,5,opt,name=spell,proto3" json:"spell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cast) Reset() {
	*x = Cast{}
	mi := &file_chronicle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cast) ProtoMessage() {}

func (x *Cast) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cast.ProtoReflect.Descriptor instead.
func (*Cast) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{10}
}

func (x *Cast) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Cast) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *Cast) GetAction() CastAction {
	if x != nil {
		return x.Action
	}
	return CastAction_ActionUnknown
}

func (x *Cast) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *Cast) GetSpell() *Spell {
	if x != nil {
		return x.Spell
	}
	return nil
}

type Aura struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	SpellName     string                 `protobuf:"bytes,3,opt,name=spellName,proto3" json:"spellName,omitempty"`
	CurrentAmount int32                  `protobuf:"varint,4,opt,name=currentAmount,proto3" json:"currentAmount,omitempty"`
	Application   AuraApplication        `protobuf:"varint,5,opt,name=application,proto3,enum=chronicleproto.AuraApplication" json:"application,omitempty"`
	State         AuraState              `protobuf:"varint,6,opt,name=state,proto3,enum=chronicleproto.AuraState" json:"state,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,7,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	IsBuff        bool                   `protobuf:"varint,8,opt,name=isBuff,proto3" json:"isBuff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aura) Reset() {
	*x = Aura{}
	mi := &file_chronicle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aura) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aura) ProtoMessage() {}

func (x *Aura) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aura.ProtoReflect.Descriptor instead.
func (*Aura) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{11}
}

func (x *Aura) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Aura) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Aura) GetSpellName() string {
	if x != nil {
		return x.SpellName
	}
	return ""
}

func (x *Aura) GetCurrentAmount() int32 {
	if x != nil {
		return x.CurrentAmount
	}
	return 0
}

func (x *Aura) GetApplication() AuraApplication {
	if x != nil {
		return x.Application
	}
	return AuraApplication_ApplicationUnknown
}

func (x *Aura) GetState() AuraState {
	if x != nil {
		return x.State
	}
	return AuraState_StateUnknown
}

func (x *Aura) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

func (x *Aura) GetIsBuff() bool {
	if x != nil {
		return x.IsBuff
	}
	return false
}

type AuraCast struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Spell           *SpellData             `protobuf:"bytes,2,opt,name=spell,proto3" json:"spell,omitempty"`
	Caster          string                 `protobuf:"bytes,3,opt,name=caster,proto3" json:"caster,omitempty"`
	Target          *string                `protobuf:"bytes,4,opt,name=target,proto3,oneof" json:"target,omitempty"`
	Effect          int32                  `protobuf:"varint,5,opt,name=effect,proto3" json:"effect,omitempty"`
	Amplitude       int32                  `protobuf:"varint,6,opt,name=amplitude,proto3" json:"amplitude,omitempty"`
	EffectMiscValue int32                  `protobuf:"varint,7,opt,name=effectMiscValue,proto3" json:"effectMiscValue,omitempty"`
	DurationMS      int32                  `protobuf:"varint,8,opt,name=durationMS,proto3" json:"durationMS,omitempty"`
	CapStatus       int32                  `protobuf:"varint,9,opt,name=capStatus,proto3" json:"capStatus,omitempty"`
	EffectAuraName  int32                  `protobuf:"varint,10,opt,name=effectAuraName,proto3" json:"effectAuraName,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuraCast) Reset() {
	*x = AuraCast{}
	mi := &file_chronicle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuraCast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuraCast) ProtoMessage() {}

func (x *AuraCast) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuraCast.ProtoReflect.Descriptor instead.
func (*AuraCast) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{12}
}

func (x *AuraCast) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AuraCast) GetSpell() *SpellData {
	if x != nil {
		return x.Spell
	}
	return nil
}

func (x *AuraCast) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *AuraCast) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *AuraCast) GetEffect() int32 {
	if x != nil {
		return x.Effect
	}
	return 0
}

func (x *AuraCast) GetAmplitude() int32 {
	if x != nil {
		return x.Amplitude
	}
	return 0
}

func (x *AuraCast) GetEffectMiscValue() int32 {
	if x != nil {
		return x.EffectMiscValue
	}
	return 0
}

func (x *AuraCast) GetDurationMS() int32 {
	if x != nil {
		return x.DurationMS
	}
	return 0
}

func (x *AuraCast) GetCapStatus() int32 {
	if x != nil {
		return x.CapStatus
	}
	return 0
}

func (x *AuraCast) GetEffectAuraName() int32 {
	if x != nil {
		return x.EffectAuraName
	}
	return 0
}

type SpellGo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ItemID        *int32                 `protobuf:"varint,2,opt,name=itemID,proto3,oneof" json:"itemID,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,3,opt,name=spellData,proto3,oneof" json:"spellData,omitempty"`
	Caster        string                 `protobuf:"bytes,4,opt,name=caster,proto3" json:"caster,omitempty"`
	Target        *string                `protobuf:"bytes,5,opt,name=target,proto3,oneof" json:"target,omitempty"`
	NumHits       int32                  `protobuf:"varint,6,opt,name=numHits,proto3" json:"numHits,omitempty"`
	NumMisses     int32                  `protobuf:"varint,7,opt,name=numMisses,proto3" json:"numMisses,omitempty"`
	CorpseOwner   *string                `protobuf:"bytes,8,opt,name=corpseOwner,proto3,oneof" json:"corpseOwner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpellGo) Reset() {
	*x = SpellGo{}
	mi := &file_chronicle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpellGo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellGo) ProtoMessage() {}

func (x *SpellGo) ProtoReflect() protoreflect.Message {
	mi := &file_chronicle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellGo.ProtoReflect.Descriptor instead.
func (*SpellGo) Descriptor() ([]byte, []int) {
	return file_chronicle_proto_rawDescGZIP(), []int{13}
}

func (x *SpellGo) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SpellGo) GetItemID() int32 {
	if x != nil && x.ItemID != nil {
		return *x.ItemID
	}
	return 0
}

func (x *SpellGo) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

func (x *SpellGo) GetCaster() string {
	if x != nil {
		return x.Caster
	}
	return ""
}

func (x *SpellGo) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *SpellGo) GetNumHits() int32 {
	if x != nil {
		return x.NumHits
	}
	return 0
}

func (x *SpellGo) GetNumMisses() int32 {
	if x != nil {
		return x.NumMisses
	}
	return 0
}

func (x *SpellGo) GetCorpseOwner() string {
	if x != nil && x.CorpseOwner != nil {
		return *x.CorpseOwner
	}
	return ""
}

var File_chronicle_proto protoreflect.FileDescriptor

const file_chronicle_proto_rawDesc = "" +
	"\n" +
	"\x0fchronicle.proto\x12\x0echronicleproto\"V\n" +
	"\tSpellData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eattack_outcome\x18\x03 \x01(\rR\rattackOutcome\"J\n" +
	"\x06Tailer\x12\x1b\n" +
	"\x06amount\x18\x01 \x01(\rH\x00R\x06amount\x88\x01\x01\x12\x18\n" +
	"\ahitType\x18\x02 \x01(\rR\ahitTypeB\t\n" +
	"\a_amount\"A\n" +
	"\rActivityEntry\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x1c\n" +
	"\teventType\x18\x02 \x01(\tR\teventType\"~\n" +
	"\tEventMeta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12 \n" +
	"\voffsetMilli\x18\x02 \x01(\x03R\voffsetMilli\x129\n" +
	"\bactivity\x18\x03 \x03(\v2\x1d.chronicleproto.ActivityEntryR\bactivity\"\xb3\x02\n" +
	"\x04Heal\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06caster\x18\x03 \x01(\tR\x06caster\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1e\n" +
	"\n" +
	"sourceName\x18\x05 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x05R\x06amount\x12\x18\n" +
	"\ahitType\x18\a \x01(\rR\ahitType\x12<\n" +
	"\tspellData\x18\b \x01(\v2\x19.chronicleproto.SpellDataH\x00R\tspellData\x88\x01\x01\x12.\n" +
	"\x06school\x18\t \x01(\x0e2\x16.chronicleproto.SchoolR\x06schoolB\f\n" +
	"\n" +
	"_spellData\"\xf7\x02\n" +
	"\x06Damage\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x1b\n" +
	"\x06caster\x18\x03 \x01(\tH\x00R\x06caster\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"sourceName\x18\x04 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x18\n" +
	"\ahitType\x18\x06 \x01(\rR\ahitType\x12\x16\n" +
	"\x06amount\x18\a \x01(\x05R\x06amount\x12.\n" +
	"\x06school\x18\b \x01(\x0e2\x16.chronicleproto.SchoolR\x06school\x120\n" +
	"\atailers\x18\t \x03(\v2\x16.chronicleproto.TailerR\atailers\x12<\n" +
	"\tspellData\x18\n" +
	" \x01(\v2\x19.chronicleproto.SpellDataH\x01R\tspellData\x88\x01\x01B\t\n" +
	"\a_casterB\f\n" +
	"\n" +
	"_spellData\"\xd9\x02\n" +
	"\x0eResourceChange\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12\"\n" +
	"\fresourceType\x18\x05 \x01(\tR\fresourceType\x12\x1b\n" +
	"\x06caster\x18\x06 \x01(\tH\x00R\x06caster\x88\x01\x01\x12#\n" +
	"\n" +
	"sourceName\x18\a \x01(\tH\x01R\n" +
	"sourceName\x88\x01\x01\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirection\x12<\n" +
	"\tspellData\x18\t \x01(\v2\x19.chronicleproto.SpellDataH\x02R\tspellData\x88\x01\x01B\t\n" +
	"\a_casterB\r\n" +
	"\v_sourceNameB\f\n" +
	"\n" +
	"_spellData\"\xd8\x01\n" +
	"\vExtraAttack\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x1e\n" +
	"\n" +
	"sourceName\x18\x05 \x01(\tR\n" +
	"sourceName\x12<\n" +
	"\tspellData\x18\x06 \x01(\v2\x19.chronicleproto.SpellDataH\x00R\tspellData\x88\x01\x01B\f\n" +
	"\n" +
	"_spellData\"\xc5\x01\n" +
	"\x05Slain\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1b\n" +
	"\x06caster\x18\x03 \x01(\tH\x00R\x06caster\x88\x01\x01\x12=\n" +
	"\vattribution\x18\x04 \x01(\v2\x16.chronicleproto.DamageH\x01R\vattribution\x88\x01\x01B\t\n" +
	"\a_casterB\x0e\n" +
	"\f_attribution\"M\n" +
	"\x05Spell\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x17\n" +
	"\x04rank\x18\x03 \x01(\x05H\x00R\x04rank\x88\x01\x01B\a\n" +
	"\x05_rank\"\xd6\x01\n" +
	"\x04Cast\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06caster\x18\x02 \x01(\tR\x06caster\x122\n" +
	"\x06action\x18\x03 \x01(\x0e2\x1a.chronicleproto.CastActionR\x06action\x12\x1b\n" +
	"\x06target\x18\x04 \x01(\tH\x00R\x06target\x88\x01\x01\x12+\n" +
	"\x05spell\x18\x05 \x01(\v2\x15.chronicleproto.SpellR\x05spellB\t\n" +
	"\a_target\"\xe9\x02\n" +
	"\x04Aura\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1c\n" +
	"\tspellName\x18\x03 \x01(\tR\tspellName\x12$\n" +
	"\rcurrentAmount\x18\x04 \x01(\x05R\rcurrentAmount\x12A\n" +
	"\vapplication\x18\x05 \x01(\x0e2\x1f.chronicleproto.AuraApplicationR\vapplication\x12/\n" +
	"\x05state\x18\x06 \x01(\x0e2\x19.chronicleproto.AuraStateR\x05state\x12<\n" +
	"\tspellData\x18\a \x01(\v2\x19.chronicleproto.SpellDataH\x00R\tspellData\x88\x01\x01\x12\x16\n" +
	"\x06isBuff\x18\b \x01(\bR\x06isBuffB\f\n" +
	"\n" +
	"_spellData\"\xf0\x02\n" +
	"\bAuraCast\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12/\n" +
	"\x05spell\x18\x02 \x01(\v2\x19.chronicleproto.SpellDataR\x05spell\x12\x16\n" +
	"\x06caster\x18\x03 \x01(\tR\x06caster\x12\x1b\n" +
	"\x06target\x18\x04 \x01(\tH\x00R\x06target\x88\x01\x01\x12\x16\n" +
	"\x06effect\x18\x05 \x01(\x05R\x06effect\x12\x1c\n" +
	"\tamplitude\x18\x06 \x01(\x05R\tamplitude\x12(\n" +
	"\x0feffectMiscValue\x18\a \x01(\x05R\x0feffectMiscValue\x12\x1e\n" +
	"\n" +
	"durationMS\x18\b \x01(\x05R\n" +
	"durationMS\x12\x1c\n" +
	"\tcapStatus\x18\t \x01(\x05R\tcapStatus\x12&\n" +
	"\x0eeffectAuraName\x18\n" +
	" \x01(\x05R\x0eeffectAuraNameB\t\n" +
	"\a_target\"\xe1\x02\n" +
	"\aSpellGo\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.chronicleproto.EventMetaR\x04meta\x12\x1b\n" +
	"\x06itemID\x18\x02 \x01(\x05H\x00R\x06itemID\x88\x01\x01\x12<\n" +
	"\tspellData\x18\x03 \x01(\v2\x19.chronicleproto.SpellDataH\x01R\tspellData\x88\x01\x01\x12\x16\n" +
	"\x06caster\x18\x04 \x01(\tR\x06caster\x12\x1b\n" +
	"\x06target\x18\x05 \x01(\tH\x02R\x06target\x88\x01\x01\x12\x18\n" +
	"\anumHits\x18\x06 \x01(\x05R\anumHits\x12\x1c\n" +
	"\tnumMisses\x18\a \x01(\x05R\tnumMisses\x12%\n" +
	"\vcorpseOwner\x18\b \x01(\tH\x03R\vcorpseOwner\x88\x01\x01B\t\n" +
	"\a_itemIDB\f\n" +
	"\n" +
	"_spellDataB\t\n" +
	"\a_targetB\x0e\n" +
	"\f_corpseOwnerJ\x04\b\t\x10\n" +
	"*p\n" +
	"\x06School\x12\v\n" +
	"\aUnknown\x10\x00\x12\b\n" +
	"\x04None\x10\x01\x12\f\n" +
	"\bPhysical\x10\x02\x12\b\n" +
	"\x04Holy\x10\x03\x12\b\n" +
	"\x04Fire\x10\x04\x12\n" +
	"\n" +
	"\x06Nature\x10\x05\x12\t\n" +
	"\x05Frost\x10\x06\x12\n" +
	"\n" +
	"\x06Shadow\x10\a\x12\n" +
	"\n" +
	"\x06Arcane\x10\b*t\n" +
	"\n" +
	"CastAction\x12\x11\n" +
	"\rActionUnknown\x10\x00\x12\x0f\n" +
	"\vActionCasts\x10\x01\x12\x16\n" +
	"\x12ActionBeginsToCast\x10\x02\x12\x12\n" +
	"\x0eActionChannels\x10\x03\x12\x16\n" +
	"\x12ActionFailsCasting\x10\x04*m\n" +
	"\x0fAuraApplication\x12\x16\n" +
	"\x12ApplicationUnknown\x10\x00\x12\x14\n" +
	"\x10ApplicationGains\x10\x01\x12\x14\n" +
	"\x10ApplicationFades\x10\x02\x12\x16\n" +
	"\x12ApplicationRemoved\x10\x03*R\n" +
	"\tAuraState\x12\x10\n" +
	"\fStateUnknown\x10\x00\x12\x0e\n" +
	"\n" +
	"StateAdded\x10\x01\x12\x10\n" +
	"\fStateRemoved\x10\x02\x12\x11\n" +
	"\rStateModified\x10\x03B/Z-github.com/Emyrk/chronicle/api/chronicleprotob\x06proto3"

var (
	file_chronicle_proto_rawDescOnce sync.Once
	file_chronicle_proto_rawDescData []byte
)

func file_chronicle_proto_rawDescGZIP() []byte {
	file_chronicle_proto_rawDescOnce.Do(func() {
		file_chronicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chronicle_proto_rawDesc), len(file_chronicle_proto_rawDesc)))
	})
	return file_chronicle_proto_rawDescData
}

var file_chronicle_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_chronicle_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_chronicle_proto_goTypes = []any{
	(School)(0),            // 0: chronicleproto.School
	(CastAction)(0),        // 1: chronicleproto.CastAction
	(AuraApplication)(0),   // 2: chronicleproto.AuraApplication
	(AuraState)(0),         // 3: chronicleproto.AuraState
	(*SpellData)(nil),      // 4: chronicleproto.SpellData
	(*Tailer)(nil),         // 5: chronicleproto.Tailer
	(*ActivityEntry)(nil),  // 6: chronicleproto.ActivityEntry
	(*EventMeta)(nil),      // 7: chronicleproto.EventMeta
	(*Heal)(nil),           // 8: chronicleproto.Heal
	(*Damage)(nil),         // 9: chronicleproto.Damage
	(*ResourceChange)(nil), // 10: chronicleproto.ResourceChange
	(*ExtraAttack)(nil),    // 11: chronicleproto.ExtraAttack
	(*Slain)(nil),          // 12: chronicleproto.Slain
	(*Spell)(nil),          // 13: chronicleproto.Spell
	(*Cast)(nil),           // 14: chronicleproto.Cast
	(*Aura)(nil),           // 15: chronicleproto.Aura
	(*AuraCast)(nil),       // 16: chronicleproto.AuraCast
	(*SpellGo)(nil),        // 17: chronicleproto.SpellGo
}
var file_chronicle_proto_depIdxs = []int32{
	6,  // 0: chronicleproto.EventMeta.activity:type_name -> chronicleproto.ActivityEntry
	7,  // 1: chronicleproto.Heal.meta:type_name -> chronicleproto.EventMeta
	4,  // 2: chronicleproto.Heal.spellData:type_name -> chronicleproto.SpellData
	0,  // 3: chronicleproto.Heal.school:type_name -> chronicleproto.School
	7,  // 4: chronicleproto.Damage.meta:type_name -> chronicleproto.EventMeta
	0,  // 5: chronicleproto.Damage.school:type_name -> chronicleproto.School
	5,  // 6: chronicleproto.Damage.tailers:type_name -> chronicleproto.Tailer
	4,  // 7: chronicleproto.Damage.spellData:type_name -> chronicleproto.SpellData
	7,  // 8: chronicleproto.ResourceChange.meta:type_name -> chronicleproto.EventMeta
	4,  // 9: chronicleproto.ResourceChange.spellData:type_name -> chronicleproto.SpellData
	7,  // 10: chronicleproto.ExtraAttack.meta:type_name -> chronicleproto.EventMeta
	4,  // 11: chronicleproto.ExtraAttack.spellData:type_name -> chronicleproto.SpellData
	7,  // 12: chronicleproto.Slain.meta:type_name -> chronicleproto.EventMeta
	9,  // 13: chronicleproto.Slain.attribution:type_name -> chronicleproto.Damage
	7,  // 14: chronicleproto.Cast.meta:type_name -> chronicleproto.EventMeta
	1,  // 15: chronicleproto.Cast.action:type_name -> chronicleproto.CastAction
	13, // 16: chronicleproto.Cast.spell:type_name -> chronicleproto.Spell
	7,  // 17: chronicleproto.Aura.meta:type_name -> chronicleproto.EventMeta
	2,  // 18: chronicleproto.Aura.application:type_name -> chronicleproto.AuraApplication
	3,  // 19: chronicleproto.Aura.state:type_name -> chronicleproto.AuraState
	4,  // 20: chronicleproto.Aura.spellData:type_name -> chronicleproto.SpellData
	7,  // 21: chronicleproto.AuraCast.meta:type_name -> chronicleproto.EventMeta
	4,  // 22: chronicleproto.AuraCast.spell:type_name -> chronicleproto.SpellData
	7,  // 23: chronicleproto.SpellGo.meta:type_name -> chronicleproto.EventMeta
	4,  // 24: chronicleproto.SpellGo.spellData:type_name -> chronicleproto.SpellData
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_chronicle_proto_init() }
func file_chronicle_proto_init() {
	if File_chronicle_proto != nil {
		return
	}
	file_chronicle_proto_msgTypes[1].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[4].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[5].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[6].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[7].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[8].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[9].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[10].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[11].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[12].OneofWrappers = []any{}
	file_chronicle_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chronicle_proto_rawDesc), len(file_chronicle_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chronicle_proto_goTypes,
		DependencyIndexes: file_chronicle_proto_depIdxs,
		EnumInfos:         file_chronicle_proto_enumTypes,
		MessageInfos:      file_chronicle_proto_msgTypes,
	}.Build()
	File_chronicle_proto = out.File
	file_chronicle_proto_goTypes = nil
	file_chronicle_proto_depIdxs = nil
}
