package cli

import (
	"fmt"
	"text/template"

	"github.com/Emyrk/chronicle/database/gamedb/chrondbc"
	"github.com/Emyrk/chronicle/database/gamedb/dbcdb"
)

type extraAttackEntry struct {
	ID              int32
	Name            string
	NumExtraAttacks int32
}

func collectExtraAttackSpells(wc *dbcdb.WoWClient) ([]extraAttackEntry, error) {
	spellsDBC, err := wc.Spells()
	if err != nil {
		return nil, fmt.Errorf("read spells: %w", err)
	}

	spells := chrondbc.NewSpells(spellsDBC.Underlying())
	var entries []extraAttackEntry

	err = spells.Range(func(spell *chrondbc.Spell) bool {
		for i, effect := range spell.Effect {
			if effect == chrondbc.EffectAddExtraAttacks {
				entries = append(entries, extraAttackEntry{
					ID:              int32(spell.ID),
					Name:            spell.String(),
					NumExtraAttacks: spell.EffectBasePoints[i] + 1,
				})
				break
			}
		}
		return true
	})
	if err != nil {
		return nil, fmt.Errorf("iterate spells: %w", err)
	}

	return entries, nil
}

var extraAttacksGoTemplate = template.Must(template.New("extraattacks-go").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

package {{.Server}}

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.ExtraAttackSpells = map[int32]dbcmem.ExtraAttackSpell{
{{- range .Entries}}
		{{.ID}}: {Name: {{printf "%q" .Name}}, NumExtraAttacks: {{.NumExtraAttacks}}},
{{- end}}
	}
}
`))

var extraAttacksTSTemplate = template.Must(template.New("extraattacks-ts").Parse(`// Code generated by scripts/dbcdata. DO NOT EDIT.

export type ExtraAttackSpell = {
  name: string;
  numExtraAttacks: number;
};

export const ExtraAttackSpells: Record<number, ExtraAttackSpell> = {
{{- range .}}
  {{.ID}}: { name: {{printf "%q" .Name}}, numExtraAttacks: {{.NumExtraAttacks}} },
{{- end}}
};
`))
