// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package datasetdb

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

func New(db DBTX) *querier {
	return &querier{db: db}
}

type querier struct {
	db DBTX
}

func (q *querier) WithTx(tx pgx.Tx) *querier {
	return &querier{
		db: tx,
	}
}
